/** Turkish strings for the approvals inbox, detail page and ApprovalCard. */
import { common } from "@/i18n/common";
import type { ApprovalKind, ApprovalStatus, Severity } from "@/lib/types";

export const approvalStrings = {
  title: "Onaylar",
  description: "Ajanların ve akışların sizden beklediği kararlar. Production istekleri en üstte ve ayrı durur.",
  tabs: { pending: "Bekleyen", decided: "Sonuçlanan" },
  back: "Onaylar",
  more: (n: number) => `${n} onay daha göster`,
  loadError: "Onaylar yüklenemedi",
  notFound: "Onay isteği bulunamadı",
  empty: {
    pending: "Bekleyen onay yok",
    pendingHint: "Ajanlar bir karar beklediğinde burada görünür.",
    decided: "Henüz sonuçlanan onay yok",
    filtered: "Bu filtrelere uyan onay yok",
    clear: "Filtreleri temizle",
  },
  sections: { production: "Production", other: "Diğer" },
  filters: {
    allKinds: "Tüm türler",
    allWorkspaces: "Tüm çalışma alanları",
    allSeverities: "Tüm önem dereceleri",
    kind: "Tür",
    workspace: "Çalışma alanı",
    severity: "Önem",
  },
  keyboard: {
    hint: "Klavye",
    move: "gez",
    approve: "onayla",
    reject: "reddet",
    open: "aç",
  },
  kinds: {
    plan: "Plan onayı",
    memory: "Hafıza önerisi",
    remote_command: "Uzak komut",
    db_write: "Veritabanı yazma",
    deploy: "Deploy",
    merge: "Birleştirme",
    final: "Son onay",
    tool_permission: "Araç izni",
    question: "Ajan sorusu",
    budget: "Bütçe",
    custom: "Kullanıcı adımı",
  } satisfies Record<ApprovalKind, string>,
  status: {
    pending: "Bekliyor",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    expired: "Süresi doldu",
    cancelled: "İptal edildi",
  } satisfies Record<ApprovalStatus, string>,
  severity: common.severity satisfies Record<Severity, string>,
  actions: {
    approve: common.approve,
    reject: common.reject,
    answer: "Yanıtla",
    choose: "Seçimi onayla",
    submit: "Gönder",
    confirmProduction: "Emin misiniz? Tekrar basın",
    cancel: common.cancel,
    details: "Ayrıntılar",
    note: "Not (isteğe bağlı)",
    rejectNote: "Reddetme nedeni (isteğe bağlı)",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    failed: "Karar kaydedilemedi",
    alreadyDecided: "Bu onay zaten sonuçlandı",
    next: "Sonraki onay",
    backToInbox: "Onay kutusuna dön",
  },
  meta: {
    requestedBy: "İsteyen",
    workspace: "Çalışma alanı",
    task: "Görev",
    session: "Oturum",
    created: "İstendi",
    expires: "Süre sonu",
    expiresIn: (t: string) => `${t} içinde sona eriyor`,
    decidedBy: "Karar veren",
    channel: "Kanal",
    note: "Not",
    agent: "Ajan",
    user: "Kullanıcı",
    engine: "Akış motoru",
    system: "Sistem",
  },
  channels: {
    app: "Uygulama",
    menubar: "Menü çubuğu",
    palette: "Palet",
    notification: "Bildirim",
    telegram: "Telegram",
    slack: "Slack",
    system: "Sistem",
  } as Record<string, string>,
  production: {
    badge: "Production",
    appOnly: "Yalnız uygulamadan onaylanabilir",
    warning: "Bu işlem production ortamını etkiler. Komutu ve hedefi dikkatle kontrol edin.",
  },
  // kind details
  plan: {
    title: "Plan",
    edit: "Düzenle",
    preview: "Önizleme",
    edited: "Düzenlendi · onaylarken düzenlenmiş plan gönderilir",
    reset: "Değişiklikleri geri al",
    empty: "Plan metni yok.",
  },
  memory: {
    file: "Dosya",
    layer: "Katman",
    rationale: "Gerekçe",
    diff: "Değişiklik",
    content: "İçerik",
    editContent: "İçeriği düzenle",
    showDiff: "Farkı göster",
    edited: "Düzenlendi · onaylarken düzenlenmiş içerik işlenir",
    boundaryWarnings: "Sınır uyarıları",
    layers: { facts: "Gerçekler", decisions: "Kararlar", boundaries: "Sınırlar", sessions: "Oturum özetleri" } as Record<string, string>,
  },
  remote: {
    command: "Komut",
    query: "Sorgu",
    host: "Host",
    database: "Veritabanı",
    environment: "Ortam",
    permission: "Yetki seviyesi",
    classification: "Sınıflandırma",
    reasons: "Nedenler",
    policy: "Politika",
    reason: "Ajanın gerekçesi",
    source: "Kaynak",
    klass: { read: "Okuma", write: "Yazma", unknown: "Bilinmiyor (yazma sayılır)" } as Record<string, string>,
    levels: { read: "Salt okuma", limited: "Sınırlı yazma", full: "Tam yetki" } as Record<string, string>,
  },
  deploy: {
    profile: "Profil",
    environment: "Ortam",
    ref: "Ref",
    summary: "Özet",
    strategy: "Strateji",
    script: "Betik",
    command: "Komut",
    workflow: "İş akışı",
    reason: "Neden onay gerekiyor",
    rollback: "Geri alma",
    targets: "Hedefler",
    healthCheck: "Sağlık kontrolü",
  },
  merge: {
    strategy: "Strateji",
    files: (n: number) => (n === 1 ? "1 dosya" : `${n} dosya`),
    more: (n: number) => `${n} dosya daha göster`,
    conflictsResolved: "Çakışmalar bir ajan tarafından çözüldü",
    strategies: { merge: "Birleştir", squash: "Squash", cherry_pick: "Cherry-pick", rebase: "Rebase" } as Record<string, string>,
    noPatch: "Değişiklik metni yok.",
  },
  final: {
    summary: "Özet",
    changes: "Değişiklikler",
    gates: "Kapılar",
    evidence: "Kanıtlar",
    gateStatus: { passed: "Geçti", failed: "Geçmedi", skipped: "Atlandı" } as Record<string, string>,
    noChanges: "Değişiklik yok.",
  },
  question: {
    answer: "Yanıtınız",
    placeholder: "Yanıtınızı yazın…",
    options: "Seçenekler",
    required: "Yanıt gerekli.",
    from: (who: string) => `${who} soruyor`,
  },
  budget: {
    provider: "Sağlayıcı",
    purpose: "Amaç",
    resets: "Sıfırlanma",
    exhausted: "Limit doldu",
    over: "Bütçe aşılıyor",
    choose: "Ne yapılsın?",
    options: {
      same_provider: "Aynı sağlayıcıyla incelemeye izin ver",
      switch: "Diğer sağlayıcıya geç",
      wait: "Limit sıfırlanınca devam et",
      continue: "Bütçeyi aşarak devam et",
    } as Record<string, string>,
  },
  tool: {
    tool: "Araç",
    command: "Komut",
    paths: "Dosyalar",
    cwd: "Dizin",
    input: "Girdi",
    policy: "Politika",
    agent: "Ajan",
  },
  custom: {
    instructions: "Yönergeler",
    input: "Girdi",
    text: "Yanıt",
    required: "Bu alan gerekli.",
    candidates: "Adaylar",
    suggested: "Önerilen",
    criteria: "Ölçütler",
    files: (n: number) => (n === 1 ? "1 dosya" : `${n} dosya`),
  },
} as const;
