/** Turkish strings for the home screen. */
export const homeStrings = {
  greeting: (hour: number) =>
    hour >= 5 && hour < 12 ? "Günaydın" : hour >= 12 && hour < 18 ? "İyi günler" : hour >= 18 && hour < 23 ? "İyi akşamlar" : "İyi geceler",
  subtitle: (workspace: string) => `${workspace} · bugün ne üzerinde çalışalım?`,
  active: {
    title: "Etkin görevler",
    elapsed: (d: string) => `${d} önce başladı`,
    queued: "Kuyrukta",
    queuedAt: (n: number) => `Kuyrukta · ${n}. sırada`,
    holdUntil: (d: string) => `${d} sonra başlayacak`,
    running: (label: string) => `${label} çalışıyor`,
    waiting: (label: string) => `${label} · seni bekliyor`,
    starting: "Başlatılıyor…",
    flow: (title: string) => `${title} akışı`,
    open: (title: string) => `Görevi aç: ${title}`,
  },
  waiting: {
    title: "Seni bekleyenler",
    viewAll: (n: number) => `Tümünü gör (${n})`,
  },
  recent: {
    title: "Son görevler",
    viewAll: "Tümü",
    error: "Son görevler yüklenemedi",
    missing: "Görev motoru henüz hazır değil; görevler studiod güncellenince burada görünür.",
    retry: "Tekrar dene",
  },
  quickStart: {
    title: "Hızlı başlangıç",
    hint: "Bir stüdyo seç ya da görevini yukarıya yaz.",
  },
  loadError: {
    title: "Çalışma alanları yüklenemedi",
    retry: "Tekrar dene",
  },
  onboarding: {
    title: "AI Studio'ya hoş geldin",
    subtitle: "Birkaç adımda ilk görevini başlatmaya hazır olacaksın.",
    steps: {
      workspace: "Çalışma alanı",
      repo: "Repo",
      cli: "Ajanlar",
      ready: "İlk görev",
    },
    stepOf: (i: number, n: number) => `Adım ${i}/${n}`,
    workspace: {
      title: "Bir çalışma alanı oluştur",
      description: "Her çalışma alanının kendi hafızası, akışları, bağlantıları ve repoları olur. Genelde bir ürün ya da proje için bir tane.",
      name: "Ad",
      placeholder: "ör. Ödeme servisi",
      create: "Oluştur",
      empty: "Bir ad girin.",
    },
    repo: {
      title: "Bir repo ekle",
      description: "Ajanlar bu repoda kendi git worktree'lerinde çalışır; ana branch'e yalnız onayınla birleşir.",
      path: "Repo yolu",
      pathPlaceholder: "/Users/sen/src/proje",
      pathHint: "Bilgisayarındaki git deposunun tam yolu.",
      name: "Görünen ad (isteğe bağlı)",
      namePlaceholder: "Klasör adı kullanılır",
      add: "Repoyu ekle",
      skip: "Şimdilik atla",
      empty: "Repo yolunu girin.",
      added: (name: string) => `“${name}” eklendi`,
    },
    cli: {
      title: "Ajan CLI'larını denetle",
      description: "AI Studio, bilgisayarındaki Claude Code ve Codex CLI'larını kullanır; girişler CLI'ın kendisinde kalır.",
      names: { claude: "Claude Code", codex: "Codex" },
      recheck: "Tekrar denetle",
      checking: "Denetleniyor…",
      ok: "Hazır",
      notInstalled: "Kurulu değil",
      loggedOut: "Giriş yapılmamış",
      incompatible: "Sürüm desteklenmiyor",
      version: (v: string) => `Sürüm ${v}`,
      testedRange: (r: string) => `Desteklenen sürümler: ${r}`,
      install: {
        claude: "npm install -g @anthropic-ai/claude-code",
        codex: "npm install -g @openai/codex",
      },
      login: {
        claude: "claude",
        codex: "codex login",
      },
      installHint: "Terminalde şunu çalıştır:",
      loginHint: {
        claude: "Terminalde claude komutunu çalıştırıp /login ile giriş yap:",
        codex: "Terminalde giriş yap:",
      },
      noneReady: "En az bir CLI hazır olunca görevler çalışabilir. Yine de devam edebilirsin.",
      error: "CLI durumu alınamadı.",
      continue: "Devam et",
    },
    ready: {
      title: "Hazırsın",
      description: "Görevini yaz, bir mod seç ve ⌘↵ ile başlat. İkili modda bir sağlayıcı yazar, diğeri inceler.",
      start: "İlk görevi yaz",
    },
    back: "Geri",
  },
} as const;
