/** Turkish strings for the Bağlantılar feature (hosts, databases, deploy, git accounts, audit, terminal). */
import type {
  CommandClass,
  DbKind,
  DeployKind,
  DeployRunStatus,
  HostAuth,
  HostingKind,
  PermissionLevel,
} from "./types";

export const connStrings = {
  title: "Bağlantılar",
  description: "Hostlar, veritabanları, deploy profilleri ve git hesapları. Gizli bilgiler yalnız Anahtar Zinciri'nde durur.",
  tabs: {
    hosts: "Hostlar",
    databases: "Veritabanları",
    deploy: "Deploy",
    git: "Git hesapları",
    audit: "Denetim kaydı",
  },
  common: {
    save: "Kaydet",
    create: "Oluştur",
    add: "Ekle",
    cancel: "Vazgeç",
    edit: "Düzenle",
    delete: "Sil",
    retry: "Tekrar dene",
    refresh: "Yenile",
    test: "Bağlantıyı test et",
    testing: "Test ediliyor…",
    open: "Aç",
    more: "Diğer işlemler",
    back: "Bağlantılar",
    none: "Yok",
    optional: "isteğe bağlı",
    loadError: "Yüklenemedi",
    saved: "Kaydedildi",
    deleted: "Silindi",
    created: (name: string) => `“${name}” eklendi`,
    deleteFailed: "Silinemedi",
    saveFailed: "Kaydedilemedi",
    unknownError: "Beklenmeyen bir hata oluştu.",
    notFound: "Bulunamadı",
    notFoundHint: "Bu kayıt silinmiş olabilir.",
    missingEndpoint: "Bu özellik motorda henüz yok",
    missingEndpointHint: "studiod güncellendiğinde burada görünecek.",
    environment: "Ortam",
    permission: "Yetki seviyesi",
    createdAt: "Eklendi",
    updatedAt: "Güncellendi",
    workspaceGlobal: "Tüm çalışma alanları",
  },
  environment: {
    hint: {
      local: "Bu Mac veya yerel ağ. Nötr renk.",
      test: "Test / staging. Amber renk.",
      production: "Canlı sistem. Kırmızı çerçeve, varsayılan salt okuma ve her yazma için ayrı onay.",
    },
    group: { production: "Production", test: "Test", local: "Yerel" },
    productionNote:
      "Production'da her yazma komutu tek tek onaylanır; “her zaman izin ver” yoktur. Onaylar varsayılan olarak yalnız uygulamadan verilir.",
  },
  permission: {
    read: "Salt okuma",
    limited: "Sınırlı yazma",
    full: "Tam yetki",
    hint: {
      read: "Okuma komutları çalışır, her yazma onay ister.",
      limited: "Yalnız tanımlı kalıplara uyan yazmalar onaysız çalışır.",
      full: "Yazmalar doğrudan çalışır (production hariç: orada her yazma yine onay ister).",
    },
    productionWide: "Production'da salt okuma dışı bir seviye seçtiniz. Yazmalar yine tek tek onaylanır.",
    patterns: "Sınırlı yazma kalıpları",
    patternsHint: "Satır başına bir kalıp; ör. systemctl restart web, docker compose up -d *",
    patternsEmpty: "Kalıp yok: her yazma onay ister.",
  } satisfies Record<PermissionLevel, string> & Record<string, unknown>,
  secret: {
    stored: "Anahtar Zinciri'nde kayıtlı",
    storedHint: "Değer hiçbir zaman gösterilmez.",
    change: "Değiştir",
    remove: "Kaldır",
    undo: "Geri al",
    willRemove: "Kaydedince kaldırılacak",
    keep: "Vazgeç",
    show: "Göster",
    hide: "Gizle",
    onceHint: "Bir kez gönderilir, Anahtar Zinciri'nde saklanır ve bir daha gösterilmez.",
  },
  hosts: {
    add: "Yeni host",
    import: "~/.ssh/config'ten içe aktar",
    emptyTitle: "Henüz host yok",
    emptyHint: "SSH hostlarını ekleyin ya da ~/.ssh/config dosyanızdan içe aktarın. Ajanlar hostlara yalnız Studio araçlarıyla dokunabilir.",
    via: (name: string) => `${name} üzerinden`,
    auth: { key: "Anahtar", password: "Parola", agent: "SSH agent" } satisfies Record<HostAuth, string>,
    terminal: "Terminal",
    openTerminal: "Terminali aç",
    terminalNeedsApproval: "Production terminali onayla açılır",
    deleteTitle: (name: string) => `“${name}” silinsin mi?`,
    deleteBody: "Host kaydı ve Anahtar Zinciri'ndeki gizli bilgileri silinir. Denetim kaydındaki geçmiş komutlar kalır.",
    form: {
      createTitle: "Yeni host",
      editTitle: (name: string) => `${name} düzenleniyor`,
      description: "SSH bağlantısı. known_hosts sıkı biçimde doğrulanır; parola ve anahtar parolası Anahtar Zinciri'nde saklanır.",
      name: "Ad",
      namePlaceholder: "ör. web-prod-1",
      hostname: "Adres",
      hostnamePlaceholder: "10.0.0.12 veya web1.ornek.com",
      port: "Port",
      username: "Kullanıcı",
      usernamePlaceholder: "deploy",
      auth: "Kimlik doğrulama",
      keyPath: "Özel anahtar dosyası",
      keyPathPlaceholder: "~/.ssh/id_ed25519",
      keyPathHint: "Bu Mac'teki yol. Dosyanın kendisi kopyalanmaz.",
      passphrase: "Anahtar parolası",
      password: "Parola",
      agentHint: "Sistemdeki ssh-agent ve varsayılan anahtar dosyaları kullanılır. Ajan süreçleri bu agent'a erişemez.",
      jumpHost: "Atlama hostu (ProxyJump)",
      jumpHostNone: "Doğrudan bağlan",
      sectionConnection: "Bağlantı",
      sectionAuth: "Kimlik doğrulama",
      sectionAccess: "Ortam ve yetki",
    },
    detail: {
      connection: "Bağlantı",
      address: "Adres",
      user: "Kullanıcı",
      authMethod: "Kimlik doğrulama",
      keyPath: "Anahtar",
      jumpHost: "Atlama hostu",
      secrets: "Gizli bilgiler",
      secretsNone: "Kayıtlı gizli bilgi yok",
      passwordStored: "Parola kayıtlı",
      passphraseStored: "Anahtar parolası kayıtlı",
      access: "Yetki",
      test: "Bağlantı testi",
      testIdle: "Bağlantıyı ve host anahtarını doğrulamak için test edin.",
      testOk: "Bağlantı başarılı",
      latency: (ms: number) => `${ms} ms`,
      agents: "Uzak CLI'lar",
      agentsHint: "Bu hostta uzak ajan çalıştırmak için Claude Code veya Codex kurulu olmalı.",
      detectAgents: "CLI'ları bul",
      agentInstalled: "Kurulu",
      agentMissing: "Bulunamadı",
      recent: "Son komutlar",
      recentEmpty: "Bu hostta henüz komut çalışmadı.",
      viewAudit: "Denetim kaydında gör",
    },
    trust: {
      unknownTitle: "Bilinmeyen host anahtarı",
      changedTitle: "Host anahtarı değişmiş!",
      unknownBody:
        "Bu hosta ilk kez bağlanılıyor. Parmak izini sunucu yöneticisiyle ya da sunucuda doğrudan karşılaştırmadan güvenmeyin.",
      changedBody:
        "Sunucu, daha önce güvendiğiniz anahtardan farklı bir anahtar sunuyor. Bu bir ortadaki adam saldırısı olabilir. Anahtarın değiştiğinden kesinlikle eminseniz değiştirin.",
      revokedTitle: "Host anahtarı iptal edilmiş",
      fingerprint: "Parmak izi",
      keyType: "Anahtar türü",
      verifyHow: "Sunucuda karşılaştırmak için",
      confirm: "Parmak izini doğruladım, bu anahtara güveniyorum",
      confirmChanged: "Anahtarın değiştiğini doğruladım, eskisini değiştir",
      trust: "Güven ve bağlan",
      replace: "Anahtarı değiştir",
      trusted: "Host anahtarı güvenilir listeye eklendi",
      trustFailed: "Host anahtarı eklenemedi",
    },
    importDialog: {
      title: "~/.ssh/config'ten içe aktar",
      description: "Seçtiğiniz Host girdileri ayrı kayıtlar olarak eklenir. Sonradan ~/.ssh/config örtük olarak okunmaz.",
      loading: "~/.ssh/config okunuyor…",
      empty: "~/.ssh/config içinde içe aktarılacak Host girdisi yok.",
      exists: "Zaten ekli",
      selectAll: "Tümünü seç",
      selected: (n: number) => (n === 0 ? "Seçim yok" : `${n} host seçildi`),
      defaults: "Eklenen hostlar için",
      submit: (n: number) => (n <= 1 ? "İçe aktar" : `${n} hostu içe aktar`),
      result: (created: number, skipped: number) =>
        skipped ? `${created} host eklendi, ${skipped} atlandı` : `${created} host eklendi`,
    },
  },
  databases: {
    add: "Yeni veritabanı",
    emptyTitle: "Henüz veritabanı yok",
    emptyHint: "PostgreSQL, MySQL/MariaDB, SQLite, MSSQL, MongoDB ve Redis desteklenir. Doğrudan ya da bir SSH hostu üzerinden tünelle bağlanılır.",
    kind: {
      postgres: "PostgreSQL",
      mysql: "MySQL / MariaDB",
      sqlite: "SQLite",
      mssql: "MSSQL",
      mongodb: "MongoDB",
      redis: "Redis",
    } satisfies Record<DbKind, string>,
    tunnel: (name: string) => `${name} tüneli`,
    console: "Sorgu konsolu",
    deleteTitle: (name: string) => `“${name}” silinsin mi?`,
    deleteBody: "Profil ve Anahtar Zinciri'ndeki parolası silinir. Denetim kaydındaki geçmiş sorgular kalır.",
    form: {
      createTitle: "Yeni veritabanı",
      editTitle: (name: string) => `${name} düzenleniyor`,
      description: "Parola Anahtar Zinciri'nde saklanır. Salt okuma seviyesinde sorgular veritabanı tarafında da salt okuma işleminde çalışır.",
      name: "Ad",
      namePlaceholder: "ör. orders-prod",
      kind: "Tür",
      host: "Sunucu",
      hostPlaceholder: "db.ornek.com",
      port: "Port",
      database: "Veritabanı",
      databasePlaceholder: "orders",
      sqlitePath: "Dosya yolu",
      sqlitePathPlaceholder: "~/Projeler/app/dev.sqlite3",
      redisDb: "Veritabanı numarası",
      username: "Kullanıcı",
      password: "Parola",
      tunnel: "SSH tüneli",
      tunnelNone: "Doğrudan bağlan",
      tunnelHint: "Bağlantı seçilen hostun üzerinden açılır; known_hosts ve yetki kuralları geçerlidir.",
    },
    detail: {
      connection: "Bağlantı",
      target: "Hedef",
      readonlyNote: "Okumalar veritabanında da salt okuma işlemi içinde çalışır (ikinci katman).",
      history: "Son sorgular",
      historyEmpty: "Henüz sorgu çalışmadı.",
    },
    consoleUi: {
      placeholder: {
        sql: "SELECT id, status, total FROM orders ORDER BY created_at DESC LIMIT 50;",
        redis: "GET oturum:42",
        mongodb: 'db.orders.find({ status: "paid" }).limit(20)',
      },
      run: "Çalıştır",
      running: "Çalışıyor…",
      waitingApproval: "Onay bekleniyor",
      waitingApprovalBody:
        "Sorgu onay kutusuna düştü. Onaylanınca çalışır ve sonuç burada görünür. Production onayları yalnız uygulamadan verilir.",
      openApprovals: "Onay kutusunu aç",
      reason: "Gerekçe",
      reasonPlaceholder: "Bu sorgu neden çalışıyor? (onay isteğinde görünür)",
      maxRows: "En fazla satır",
      classifying: "Sınıflandırılıyor…",
      emptyQuery: "Bir sorgu yazın; çalıştırmadan önce nasıl sınıflandığını burada görürsünüz.",
      segments: (n: number) => `${n} ifade ayrı ayrı değerlendirildi`,
      denied: "Sorgu reddedildi",
      failed: "Sorgu başarısız",
      results: "Sonuç",
      rows: (n: number) => (n === 1 ? "1 satır" : `${n} satır`),
      truncated: (n: number) => `İlk ${n} satır gösteriliyor`,
      noRows: "Sorgu çalıştı, satır dönmedi.",
      approvedBy: (who: string) => `Onaylayan: ${who}`,
      copyTsv: "Sonucu kopyala (TSV)",
      shortcut: "⌘↵ ile çalıştır",
    },
  },
  classification: {
    read: "Okuma",
    write: "Yazma",
    unknown: "Bilinmiyor",
    unknownNote: "Tanınmayan komut yazma sayılır.",
    unparsed: "Ayrıştırılamadı; güvenli tarafta kalınarak yazma sayıldı.",
    expectation: {
      allowRead: "Doğrudan çalışır",
      allowReadTx: "Doğrudan çalışır · salt okuma işlemi açılır",
      allowWrite: "Tam yetki: doğrudan çalışır",
      limitedMaybe: "Sınırlı yazma: kalıplara uyuyorsa doğrudan, uymuyorsa onayla çalışır",
      approveProduction: "Production yazması: bu sorgu için ayrı onay gerekir",
      approveRead: "Salt okuma seviyesi: yazma onay gerektirir",
    },
  } satisfies Record<CommandClass, string> & Record<string, unknown>,
  deploy: {
    add: "Yeni deploy profili",
    emptyTitle: "Henüz deploy profili yok",
    emptyHint: "CI iş akışı tetikleme, SSH hostlarında betik çalıştırma veya yerel komut. Production deploy'ları kilitli onaydan geçer.",
    noWorkspace: "Deploy profilleri bir çalışma alanına bağlıdır. Önce bir çalışma alanı oluşturun.",
    kind: { ci: "CI", ssh: "SSH", command: "Komut" } satisfies Record<DeployKind, string>,
    kindHint: {
      ci: "GitHub Actions iş akışı veya GitLab pipeline'ı değişkenlerle tetiklenir ve bitene kadar izlenir.",
      ssh: "Bir veya birden fazla hostta betik çalışır (sıralı veya kademeli). remote.exec politikaları geçerlidir.",
      command: "Bu Mac'te yerel bir komut çalışır.",
    } satisfies Record<DeployKind, string>,
    status: {
      pending_approval: "Onay bekliyor",
      running: "Çalışıyor",
      succeeded: "Başarılı",
      failed: "Başarısız",
      rejected: "Reddedildi",
      cancelled: "İptal edildi",
    } satisfies Record<DeployRunStatus, string>,
    run: "Deploy et",
    rollback: "Geri al",
    rollbackStarted: "Geri alma başlatıldı",
    cancel: "İptal et",
    cancelled: "Deploy iptal edildi",
    started: "Deploy başlatıldı",
    startedApproval: "Deploy onay bekliyor",
    lastRun: "Son deploy",
    never: "Henüz deploy yok",
    hosts: (n: number) => (n === 1 ? "1 host" : `${n} host`),
    healthUrl: "Sağlık kontrolü: URL",
    healthCommand: "Sağlık kontrolü: komut",
    healthNone: "Sağlık kontrolü yok",
    rollbackDefined: "Tek tıkla geri alma tanımlı",
    rollbackNone: "Geri alma tanımlı değil",
    deleteTitle: (name: string) => `“${name}” silinsin mi?`,
    deleteBody: "Profil silinir. Ortamın deploy geçmişi kalır.",
    form: {
      createTitle: "Yeni deploy profili",
      editTitle: (name: string) => `${name} düzenleniyor`,
      description: "Deploy bir akış düğümüdür; önceki kapılar geçilmiş olmalıdır. Production'da onay kilitlidir.",
      name: "Ad",
      namePlaceholder: "ör. web — production",
      kind: "Tür",
      kindLocked: "Tür sonradan değiştirilemez.",
      repo: "Repo kimliği",
      repoPlaceholder: "repo_…",
      repoHint: "Çalışma alanındaki repo kaydı (GitHub veya GitLab hesabına bağlı).",
      workflow: "İş akışı",
      workflowPlaceholder: "deploy.yml",
      workflowHint: "GitHub'da iş akışı dosyası ya da adı. GitLab pipeline'ları için boş bırakın.",
      variables: "Değişkenler",
      variablesHint: "Satır başına ANAHTAR=değer",
      hosts: "Hostlar",
      hostsEmpty: "Önce Hostlar sekmesinden bir SSH hostu ekleyin.",
      script: "Betik",
      scriptPlaceholder: "cd /srv/web && git pull && systemctl restart web",
      strategy: "Strateji",
      strategySequential: "Sıralı",
      strategyRolling: "Kademeli",
      batchSize: "Grup boyutu",
      cwd: "Çalışma dizini",
      command: "Komut",
      commandPlaceholder: "./scripts/deploy.sh",
      env: "Ortam değişkenleri",
      timeout: "Zaman aşımı (sn)",
      health: "Sağlık kontrolü",
      healthKind: { none: "Yok", url: "URL", command: "Komut" },
      healthUrl: "Adres",
      healthUrlPlaceholder: "https://ornek.com/healthz",
      healthExpect: "Beklenen durum kodları",
      healthExpectPlaceholder: "200, 204",
      healthCommand: "Komut",
      healthCommandPlaceholder: "curl -fsS localhost:8080/healthz",
      healthHost: "Çalışacağı host",
      healthHostLocal: "Bu Mac",
      rollback: "Geri alma",
      rollbackToggle: "Tek tıkla geri alma tanımla",
      rollbackHint: "Deploy başarısız olursa geçmişten tek tıkla çalıştırılır.",
      rollbackWorkflow: "Geri alma iş akışı",
      rollbackScript: "Geri alma betiği",
      rollbackCommand: "Geri alma komutu",
      sectionTarget: "Hedef",
      sectionHealth: "Doğrulama",
    },
    runDialog: {
      title: (name: string) => `${name} deploy edilsin mi?`,
      ref: "Ref",
      refPlaceholder: "main, v1.4.2 veya bir commit",
      summary: "Değişiklik özeti",
      summaryPlaceholder: "Bu deploy neyi değiştiriyor?",
      summaryRequired: "Production deploy için değişiklik özeti gerekli.",
      productionTitle: "Production deploy kilitli onaydan geçer",
      productionSteps: [
        "Başlattığınızda onay isteği Onay kutusuna düşer; onaylanmadan hiçbir komut çalışmaz.",
        "Onay varsayılan olarak yalnız uygulamadan verilir (Ayarlar › Güvenlik).",
        "Bittiğinde sağlık kontrolü çalışır; başarısızsa tanımlıysa tek tıkla geri alınabilir.",
      ],
      approvalNeeded: "Bu deploy onay gerektirebilir (ör. tam yetkisi olmayan hostlar).",
      submit: "Deploy et",
      submitProduction: "Onaya gönder",
    },
    detail: {
      config: "Yapılandırma",
      runs: "Deploy geçmişi",
      runsEmpty: "Bu profil henüz deploy edilmedi.",
      log: "Günlük",
      logEmpty: "Günlük henüz boş.",
      waitingApproval: "Onay bekleniyor",
      waitingApprovalBody: "Onaylanınca deploy başlar. Production onayları yalnız uygulamadan verilir.",
      openApproval: "Onayı aç",
      health: (ok: boolean) => (ok ? "Sağlık kontrolü geçti" : "Sağlık kontrolü başarısız"),
      approvedBy: (who: string) => `Onaylayan: ${who}`,
      rollbackOf: "Geri alma",
      by: (actor: string) => `Başlatan: ${actor}`,
      selectRun: "Günlüğü görmek için bir deploy seçin.",
    },
  },
  git: {
    add: "Hesap ekle",
    emptyTitle: "Henüz git hesabı yok",
    emptyHint: "GitHub veya GitLab (kendi sunucunuz dahil) kişisel erişim belirteciyle bağlanır. Belirteç Anahtar Zinciri'nde saklanır.",
    kind: { github: "GitHub", gitlab: "GitLab" } satisfies Record<HostingKind, string>,
    verify: "Doğrula",
    verified: "Belirteç geçerli",
    verifyFailed: "Doğrulanamadı",
    repos: "Repolar",
    reposEmpty: "Bu hesapta repo bulunamadı.",
    reposSearch: "Repo ara",
    reposCount: (n: number) => `${n} repo`,
    private: "Özel",
    scopes: "Yetkiler",
    scopesNone: "Yetki bilgisi yok",
    deleteTitle: (name: string) => `“${name}” kaldırılsın mı?`,
    deleteBody: "Hesap ve Anahtar Zinciri'ndeki belirteci silinir. Bu hesaba bağlı repolar başka bir hesapla eşleşene kadar PR işlemleri yapamaz.",
    form: {
      title: "Git hesabı ekle",
      description: "Belirteç bir kez gönderilir, doğrulanır ve Anahtar Zinciri'nde saklanır.",
      kind: "Sağlayıcı",
      selfHosted: "Kendi sunucum",
      selfHostedHint: "GitHub Enterprise veya kendi GitLab sunucunuz",
      server: "Sunucu adresi",
      serverPlaceholder: "https://gitlab.sirket.com",
      token: "Kişisel erişim belirteci",
      name: "Görünen ad",
      namePlaceholder: "Boş bırakılırsa kullanıcı@sunucu",
      helpTitle: "Belirteç nasıl alınır?",
      createToken: "Belirteç sayfasını aç",
      submit: "Doğrula ve ekle",
      verifying: "Doğrulanıyor…",
    },
    help: {
      github: [
        "GitHub › Settings › Developer settings › Personal access tokens sayfasını açın.",
        "Klasik belirteç için repo, workflow ve read:org yetkilerini seçin (ince ayarlı belirteçte: Contents, Pull requests, Actions ve Issues okuma/yazma).",
        "Belirteci kopyalayıp buraya yapıştırın; bir daha gösterilmez.",
      ],
      gitlab: [
        "GitLab › Edit profile › Access tokens sayfasını açın.",
        "api, read_repository ve write_repository yetkilerini seçin; bir son kullanma tarihi belirleyin.",
        "Belirteci kopyalayıp buraya yapıştırın; bir daha gösterilmez.",
      ],
    } satisfies Record<HostingKind, string[]>,
  },
  audit: {
    title: "Denetim kaydı",
    description: "Her uzak komut ve veritabanı sorgusu: kim çalıştırdı, nasıl sınıflandı, kim onayladı. Kayıt değiştirilemez ve zincirlidir.",
    emptyTitle: "Henüz kayıt yok",
    emptyHint: "Uzak komutlar ve sorgular çalıştıkça burada görünür.",
    search: "Komut, hedef veya gerekçe ara",
    filters: {
      kind: { all: "Tümü", host: "Komutlar", db: "Sorgular" },
      env: "Ortam",
      envAll: "Tüm ortamlar",
      klass: "Sınıf",
      klassAll: "Tüm sınıflar",
      deniedOnly: "Yalnız reddedilenler",
    },
    columns: { time: "Zaman", target: "Hedef", actor: "Kim", command: "Komut", klass: "Sınıf", outcome: "Sonuç" },
    actor: { user: "Siz", system: "Sistem", agent: (id: string) => `Ajan · ${id}` },
    outcome: {
      executed: "Çalıştı",
      denied: "Reddedildi",
      rejected: "Onay verilmedi",
      failed: "Başarısız",
      terminal: "Terminal",
    } as Record<string, string>,
    exit: (code: number) => `çıkış ${code}`,
    rows: (n: number) => `${n} satır`,
    loadMore: "Daha eski kayıtlar",
    export: "Dışa aktar",
    exportCsv: "CSV olarak indir",
    exportJson: "JSON olarak indir",
    exportFailed: "Dışa aktarılamadı",
    details: {
      reasons: "Sınıflandırma gerekçeleri",
      approval: "Onay",
      approvedBy: "Onaylayan",
      reason: "Gerekçe",
      output: "Çıktı (maskeli)",
      error: "Hata",
      denial: "Ret gerekçesi",
      source: "Kaynak",
      hash: "Kayıt özeti",
      duration: "Süre",
    },
    preview: "Son kayıtlar",
    viewAll: "Tüm kaydı aç",
  },
  terminal: {
    title: (name: string) => `${name} terminali`,
    status: {
      idle: "Hazırlanıyor",
      connecting: "Bağlanıyor…",
      waiting_approval: "Onay bekleniyor",
      open: "Bağlı",
      closed: "Kapandı",
      error: "Hata",
    },
    waitingTitle: "Production terminali onay bekliyor",
    waitingBody:
      "Bu host production ortamında. Etkileşimli terminal ancak onaylandıktan sonra açılır; yazdığınız her satır denetim kaydına düşer. Onay yalnız uygulamadan verilebilir.",
    openApproval: "Onayı aç",
    exited: (code: number | null) => (code === null ? "Oturum kapandı." : `Oturum kapandı (çıkış kodu ${code}).`),
    reconnect: "Yeniden bağlan",
    disconnect: "Bağlantıyı kes",
    auditNote: "Her satır denetim kaydına yazılır · parola istemlerine girilenler kaydedilmez",
    lostConnection: "Bağlantı koptu.",
  },
} as const;
