/** Turkish strings for Ayarlar. */
import type { DeliveryStatus, RemoteAccess, SandboxLevel } from "./types";

export const setStrings = {
  title: "Ayarlar",
  sections: {
    appearance: { title: "Görünüm", description: "Tema ve hareket tercihleri. Değişiklikler anında uygulanır." },
    profiles: { title: "Ajan profilleri", description: "Sağlayıcı, model, rol ve sınırlar. Hazır profiller düzenlenebilir ama silinemez." },
    clis: { title: "CLI durumu", description: "Claude Code ve Codex kurulumu, oturum durumu ve uyumluluk; bu Mac'te ve hostlarda." },
    limits: { title: "Limitler ve bütçe", description: "Uyarı eşiği, sorgulama sıklığı ve yeni görevler için varsayılan bütçe." },
    alerts: { title: "Uyarılar", description: "Kanallar, yönlendirme kuralları, sessiz saatler ve teslim kaydı." },
    safety: { title: "Güvenlik", description: "Production kuralları ve production onaylarının nereden verilebileceği." },
    shortcuts: { title: "Kısayollar", description: "Uygulama arka plandayken hızlı paleti açan genel kısayol ve uygulama içi kısayollar." },
    backup: { title: "Yedekleme", description: "studio.db ve hafıza repolarının zamanlanmış yedekleri; uygulama içinden geri yükleme." },
    about: { title: "Hakkında", description: "Sürümler, motor modülleri ve yerel kabuk durumu." },
  },
  common: {
    save: "Kaydet",
    done: "Tamam",
    saved: "Kaydedildi",
    saveFailed: "Kaydedilemedi",
    cancel: "Vazgeç",
    create: "Oluştur",
    add: "Ekle",
    edit: "Düzenle",
    delete: "Sil",
    deleted: "Silindi",
    refresh: "Yenile",
    enabled: "Etkin",
    disabled: "Kapalı",
    more: "Diğer işlemler",
    browserOnly: "Yalnız masaüstü uygulamasında",
    browserOnlyHint: "Tarayıcıda çalışıyorsunuz; bu ayar AI Studio uygulamasında etkinleşir.",
    defaultValue: (v: string) => `Varsayılan: ${v}`,
  },
  appearance: {
    theme: "Tema",
    themeHint: "Sistem, macOS görünümünü izler.",
    themes: { system: "Sistem", light: "Açık", dark: "Koyu" },
    motion: "Hareketi azalt",
    motionHint: "Açıkken geçişler yumuşak solmaya iner; yaylar ve döngüler durur.",
    motionOptions: { system: "Sistem", on: "Açık", off: "Kapalı" },
    motionSystemNote: (on: boolean) => (on ? "macOS'ta “Hareketi azalt” açık." : "macOS'ta “Hareketi azalt” kapalı."),
    preview: "Önizleme",
  },
  profiles: {
    add: "Yeni profil",
    builtin: "Hazır",
    builtinLocked: "Hazır profiller silinemez; düzenleyebilirsiniz.",
    emptyTitle: "Profil yok",
    model: "Model",
    modelDefault: "CLI varsayılanı",
    effort: "Efor",
    effortDefault: "Varsayılan",
    role: "Rol",
    sandbox: { read_only: "Salt okuma", workspace_write: "Çalışma alanına yazma", full: "Tam erişim" } satisfies Record<SandboxLevel, string>,
    sandboxHint: { read_only: "Dosya değiştiremez.", workspace_write: "Yalnız kendi worktree'sine yazar.", full: "Sandbox yok; dikkatli kullanın." } satisfies Record<SandboxLevel, string>,
    remote: { none: "Yok", read: "Salt okuma", limited: "Sınırlı", full: "Tam" } satisfies Record<RemoteAccess, string>,
    network: "Ağ erişimi",
    deleteTitle: (name: string) => `“${name}” silinsin mi?`,
    deleteBody: "Profil silinir. Bu profili kullanan akış düğümleri varsayılan profile döner.",
    form: {
      createTitle: "Yeni ajan profili",
      editTitle: (name: string) => `${name} düzenleniyor`,
      description: "Sınırlar dört katmanda uygulanır: CLI ayarları, izin yakalama, sınır denetimi kapısı ve uzak erişimde Studio araçları.",
      name: "Ad",
      namePlaceholder: "ör. Claude hata ayıklayıcı",
      provider: "Sağlayıcı",
      model: "Model",
      modelPlaceholder: "Boş: CLI varsayılanı",
      instructions: "Ek talimatlar",
      instructionsHint: "Sistem istemine eklenir.",
      sectionIdentity: "Kimlik",
      sectionBoundaries: "Sınırlar",
      sandbox: "Sandbox",
      remoteAccess: "Uzak erişim",
      remoteAccessHint: "Uzak sistemlere yalnız remote.exec ve db.query araçlarıyla dokunur.",
      forbidden: "Dokunulmayacak yollar",
      readonly: "Salt okunur yollar",
      allowed: "İzinli komutlar",
      denied: "Yasak komutlar",
      linesHint: "Satır başına bir kalıp",
    },
    behavior: "Ajan davranışı",
    stallMinutes: "Takıldı sayılma süresi",
    stallMinutesHint: "Bu kadar dakika çıktı üretmeyen ajan için kritik uyarı gönderilir.",
    permissionTimeout: "İzin bekleme süresi",
    permissionTimeoutHint: "0: karar verilene kadar bekler.",
    minutes: "dk",
  },
  clis: {
    local: "Bu Mac",
    host: "Host",
    hostPick: "Bir host seçin",
    hostsEmpty: "Henüz SSH hostu yok.",
    installed: "Kurulu",
    missing: "Kurulu değil",
    loggedIn: "Oturum açık",
    loggedOut: "Oturum kapalı",
    loginUnknown: "Oturum durumu bilinmiyor",
    compatible: "Uyumlu",
    incompatible: "Test edilmemiş sürüm",
    testedRange: (r: string) => `Test edilen aralık: ${r}`,
    install: "Kurulum",
    login: "Giriş",
    verifyTitle: "Gerçek CLI doğrulaması",
    verifyBody: "Bu Mac'teki gerçek Claude Code ve Codex CLI'larını uçtan uca doğrular (biraz kota kullanır) ve bir rapor üretir. Repo kökünde çalıştırın:",
    hints: {
      claude: { install: "npm install -g @anthropic-ai/claude-code", login: "claude   # ardından /login" },
      codex: { install: "npm install -g @openai/codex   # veya: brew install codex", login: "codex login" },
    },
  },
  limits: {
    current: "Şu anki kullanım",
    refresh: "Limitleri yenile",
    refreshed: "Limitler yenilendi",
    available: "Kullanılabilir",
    unavailable: "Dolu",
    source: { event: "CLI olayı", probe: "Sorgu", estimate: "Tahmin" } as Record<string, string>,
    observed: (rel: string) => `${rel} güncellendi`,
    empty: "Henüz limit bilgisi yok. Ajanlar çalıştıkça dolar.",
    warning: "Uyarı eşiği",
    warningHint: "Bir pencere bu yüzdeyi geçince “limit %X” uyarısı gönderilir.",
    refreshMinutes: "Sorgulama sıklığı",
    refreshMinutesHint: "Limit harcamayan sorgularla son değer güncellenir.",
    refreshOptions: { 0: "Kapalı", 1: "1 dk", 5: "5 dk", 15: "15 dk", 30: "30 dk" } as Record<number, string>,
    budget: "Varsayılan görev bütçesi",
    budgetHint: "Abonelikte dolar anlamsız olduğu için bütçe limit yüzdesiyle tanımlanır. Boş alan sınır yok demektir.",
    fiveHour: "5 saatlik pencerenin en fazla",
    weekly: "Haftalık pencerenin en fazla",
    duration: "En uzun süre",
    turns: "En fazla tur",
    percent: "%",
    minutes: "dk",
    policy: "Limit dolunca",
    policyOptions: { switch_provider: "Diğer sağlayıcıya geç", queue: "Sıfırlanana kadar beklet", ask: "Bana sor" },
    policyHint: "Akışlar kendi politikalarını seçebilir; bu, yeni akışların varsayılanıdır.",
    budgetSaved: "Varsayılan bütçe kaydedildi",
  },
  alerts: {
    master: "Uyarılar",
    masterHint: "Kapalıyken yalnız uygulama içi bildirimler görünür.",
    channels: "Kanallar",
    channelsHint: "Tek yönlü kanallar bildirir; Telegram ve Slack (Socket Mode) ile onay da verilebilir.",
    addChannel: "Kanal ekle",
    chooseKind: "Kanal türü seçin",
    noChannels: "Henüz kanal yok",
    noChannelsHint: "macOS bildirimi ile başlayın; telefona push için ntfy, Telegram veya Slack ekleyin.",
    twoWay: "Çift yönlü",
    listening: "Dinliyor",
    notListening: "Bağlantı bekleniyor",
    test: "Test gönder",
    testSent: "Test bildirimi gönderildi",
    testFailed: "Test bildirimi gönderilemedi",
    link: "Hesabı bağla",
    linked: "Hesap bağlandı",
    linkTitle: "Hesabınızı bağlayın",
    linkBody: "Yalnız bağlanmış kullanıcı kimliği onay verebilir. Kodu 10 dakika içinde gönderin.",
    linkWaiting: "Mesajınız bekleniyor…",
    linkExpired: "Kodun süresi doldu.",
    linkNew: "Yeni kod al",
    linkExpires: (left: string) => `${left} içinde geçersiz olur`,
    primary: "Birincil mobil kanal",
    primaryHint: "Yüksek önemdeki uyarılar macOS'a ek olarak buraya gider. Otomatik: ilk etkin Telegram, Slack ya da ntfy.",
    primaryAuto: "Otomatik",
    deleteTitle: (name: string) => `“${name}” silinsin mi?`,
    deleteBody: "Kanal ve Anahtar Zinciri'ndeki gizli bilgileri silinir. Bu kanalı kullanan kurallar ondan arındırılır.",
    channelForm: {
      createTitle: (label: string) => `${label} kanalı`,
      editTitle: (name: string) => `${name} düzenleniyor`,
      name: "Ad",
      enabled: "Etkin",
      secretStored: "Kayıtlı (boş bırakırsanız korunur)",
    },
    routing: "Varsayılan yönlendirme",
    routingHint: "Etkin bir kural uyan uyarının yönlendirmesini değiştirir.",
    bypassesQuiet: "Sessiz saatleri deler",
    rules: "Kurallar",
    rulesHint: "Olay türü, en düşük önem ve çalışma alanına göre kanal seçin. Kanalsız kural uyarıyı susturur.",
    addRule: "Kural ekle",
    noRules: "Kural yok; varsayılan yönlendirme geçerli.",
    ruleForm: {
      createTitle: "Yeni uyarı kuralı",
      editTitle: (name: string) => `${name} düzenleniyor`,
      name: "Ad",
      namePlaceholder: "ör. Production olayları telefona",
      events: "Olay türleri",
      eventsHint: "Boş: tüm olaylar. Özel tür için “pr.*” gibi yazıp Enter'a basın.",
      customEvent: "Özel olay türü",
      customEventInvalid: "“pr.review” ya da “pr.*” biçiminde olmalı.",
      severity: "En düşük önem",
      workspace: "Çalışma alanı",
      workspaceAll: "Tüm çalışma alanları",
      channels: "Kanallar",
      channelsEmpty: "Kanal seçilmedi: uyan uyarılar susturulur.",
      sound: "Sesli bildir",
      bypassQuiet: "Sessiz saatleri deler",
    },
    allEvents: "Tüm olaylar",
    mutes: "Susturur",
    quiet: "Sessiz saatler",
    quietHint: "Kritik uyarılar sessiz saatleri her zaman deler.",
    quietEnabled: "Sessiz saatler",
    quietNow: "Şu an sessiz saatlerdesiniz",
    from: "Başlangıç",
    to: "Bitiş",
    days: "Günler",
    timezone: "Saat dilimi",
    timezoneSystem: (tz: string) => `Bu Mac (${tz})`,
    quietSaved: "Sessiz saatler kaydedildi",
    advanced: "Gelişmiş",
    dedup: "Aynı olayı birleştirme süresi",
    group: "Gruplama penceresi",
    rate: "Kanal başına dakikada en fazla",
    confirmTimeout: "İkinci doğrulama süresi",
    seconds: "sn",
    perMinute: "uyarı",
    log: "Teslim kaydı",
    logHint: "Son gönderimler; hata ayrıntısı için satırın üzerine gelin.",
    logEmpty: "Henüz gönderim yok.",
    logFilter: "Durum",
    logAll: "Tümü",
    status: {
      sent: "Gönderildi",
      failed: "Başarısız",
      suppressed: "Bastırıldı",
      rate_limited: "Hız sınırı",
      deduplicated: "Birleştirildi",
      grouped: "Gruplandı",
    } satisfies Record<DeliveryStatus, string>,
    testTag: "test",
  },
  safety: {
    rulesTitle: "Production kuralları",
    rules: [
      { title: "Kırmızı çerçeve", body: "Production bağlamı etkinken pencerenin etrafında ince kırmızı bir çerçeve ve etiket görünür." },
      { title: "Varsayılan salt okuma", body: "Production hostları ve veritabanları salt okuma seviyesiyle başlar." },
      { title: "Komut başına onay", body: "Production'daki her yazma komutu ve deploy tek tek onaylanır." },
      { title: "“Her zaman izin ver” yok", body: "Production için kalıcı izin verilemez; production kapıları kapatılamaz." },
      { title: "Onaylar uygulamadan", body: "Production onayları varsayılan olarak yalnız uygulamadan verilir." },
    ],
    remoteTitle: "Kanallardan production onayına izin ver",
    remoteBody: "Açılırsa production onayları Telegram ve Slack'ten de verilebilir. Yalnız bağlanmış kullanıcı kimliği onay verebilir ve ikinci bir doğrulama istenir.",
    on: "Kanallara açık",
    off: "Yalnız uygulamadan",
    confirmTitle: "Production onaylarını kanallara aç",
    confirmBody: "Telefonunuz ya da sohbet hesabınız ele geçirilirse production'da yazma komutları ve deploy'lar onaylanabilir. Yalnız gerçekten gerekiyorsa açın.",
    confirmChecks: [
      "Yalnız bağladığım kullanıcı kimliğinin onay verebileceğini anlıyorum.",
      "Her onayda ikinci bir doğrulama isteneceğini anlıyorum.",
      "Bu ayarı istediğim zaman kapatabileceğimi biliyorum.",
    ],
    confirmType: "production",
    confirm: "Kanallara aç",
    enabledToast: "Production onayları kanallara açıldı",
    disabledToast: "Production onayları yalnız uygulamadan verilecek",
  },
  shortcuts: {
    global: "Hızlı palet",
    globalHint: "Uygulama arka plandayken de yüzen paleti açar.",
    record: "Değiştir",
    recording: "Kısayolu basın…",
    recordingHint: "En az bir değiştirici (⌘, ⌃ veya ⌥) · Esc ile vazgeç",
    reset: "Varsayılana dön",
    registered: "Kayıtlı",
    notRegistered: "Kayıtlı değil",
    saved: (label: string) => `Genel kısayol: ${label}`,
    failed: "Kısayol kaydedilemedi",
    inApp: "Uygulama içi kısayollar",
    inAppHint: "Değiştirilemez; komut paletinde de görünür.",
    palette: "Komut paleti",
    newTask: "Yeni görev",
    sidebar: "Kenar çubuğunu daralt / genişlet",
  },
  backup: {
    now: "Şimdi yedekle",
    created: "Yedek alındı",
    failed: "Yedek alınamadı",
    schedule: "Zamanlama",
    interval: "Sıklık",
    keep: "Saklanacak yedek",
    keepHint: "Daha eski zamanlanmış yedekler silinir.",
    dir: "Klasör",
    dirHint: "iCloud Drive veya harici bir disk seçebilirsiniz. Boş: varsayılan klasör.",
    dirReset: "Varsayılan",
    reveal: "Finder'da göster",
    last: "Son yedek",
    next: "Sonraki",
    never: "Henüz yok",
    list: "Yedekler",
    empty: "Henüz yedek yok",
    emptyHint: "İlk yedeği şimdi alabilirsiniz.",
    reason: { manual: "Elle", scheduled: "Zamanlanmış", "pre-restore": "Geri yükleme öncesi" },
    workspaces: (n: number) => (n === 1 ? "1 çalışma alanı" : `${n} çalışma alanı`),
    restore: "Geri yükle",
    restoreTitle: (name: string) => `${name} geri yüklensin mi?`,
    restoreBody: "Şu anki studio.db ve hafıza repoları bu yedektekilerle değiştirilir. Sonrasında motorun yeniden başlatılması gerekir.",
    safety: "Önce şu anki durumun yedeğini al",
    safetyHint: "Önerilir: geri yüklemeden vazgeçerseniz bu yedeğe dönebilirsiniz.",
    restored: "Geri yükleme tamamlandı",
    restartNeeded: "Değişikliklerin geçerli olması için motoru yeniden başlatın.",
    restart: "Motoru yeniden başlat",
    restarting: "Motor yeniden başlatılıyor",
  },
  about: {
    app: "AI Studio",
    version: "Sürüm",
    engine: "Motor (studiod)",
    modules: "Modüller",
    mode: "Mod",
    dev: "Geliştirme",
    prod: "Üretim",
    lastEvent: "Son olay",
    shell: "Yerel kabuk",
    shellNone: "Tarayıcıda çalışıyor; yerel kabuk bilgisi yok.",
    platform: "Platform",
    notifications: "Bildirim izni",
    openNotificationSettings: "Bildirim ayarlarını aç",
    paused: "Bildirimler duraklatıldı",
    permission: { granted: "Verildi", denied: "Reddedildi", "not-determined": "Sorulmadı", fallback: "Yedek yöntem", unsupported: "Desteklenmiyor" } as Record<string, string>,
    backend: "Motor süreci",
    running: "Çalışıyor",
    stopped: "Durdu",
    dataDir: "Veri klasörü",
    logFile: "Günlük dosyası",
    reveal: "Finder'da göster",
  },
} as const;
