/** Turkish strings of the flows feature (editor, list, schedules). */
import type { AgentOutputFormat, EdgeCondition, FlowMode, GateKind, MergeStrategy, NodeKind, OnExhausted, RemoteAccess, SandboxLevel, SynthesisOutputFormat } from "./types";

export const kindStrings: Record<NodeKind, { label: string; description: string; long: string }> = {
  agent: { label: "Ajan", description: "Kod yazar, kendi worktree'sinde", long: "Kod yazan ajan adımı. Kendi worktree'sinde çalışır." },
  advisor: { label: "Danışman", description: "Salt okuma, görüş belgesi yazar", long: "Kod yazmaz; repoyu okuyup görüş belgesi üretir." },
  gate: { label: "Kapı", description: "Build/test, inceleme ya da onay", long: "Geçilmeden ilerlenemeyen kontrol noktası." },
  parallel: { label: "Paralel", description: "Dalları aynı anda başlatır", long: "Bu düğümden çıkan tüm dalları aynı anda başlatır." },
  join: { label: "Birleşme", description: "Dalların hepsini ya da ilkini bekler", long: "Gelen dalların hepsini ya da ilk biteni bekler." },
  compare: { label: "Karşılaştır", description: "Yarış sonuçlarından birini seçer", long: "Yarış sonuçlarında kapıları çalıştırır; sen ya da hakem seçer." },
  condition: { label: "Koşul", description: "Çıktıya göre yol ayırır", long: "Bir ifadeye göre doğru ya da yanlış yolunu izler." },
  synthesis: { label: "Sentez", description: "Görüşlerden tek karar yazar", long: "Görüşleri toplar, karşı tez ister ve tek karar belgesi yazar." },
  merge: { label: "Merge", description: "Worktree'yi branch'e birleştirir", long: "Seçilen worktree'yi hedef branch'e birleştirir." },
  git: { label: "Git", description: "Push yapar ya da PR/MR açar", long: "Push yapar ya da PR/MR açar; istersen PR'ı takip eder." },
  deploy: { label: "Deploy", description: "Deploy profilini çalıştırır", long: "Seçilen deploy profilini çalıştırır." },
  human: { label: "İnsan", description: "Senden girdi ya da elle adım", long: "Senden girdi ister ya da elle yapılacak bir adımı bekler." },
  team: { label: "Ekip", description: "Lider, üyeler ve test ajanları", long: "Lider görevi alır, işi ekibe böler; üyeler kendi worktree'lerinde çalışır, sonuçlar yukarı birleşir." },
};

export const gateStrings: Record<GateKind, { label: string; short: string; description: string }> = {
  plan_approval: { label: "Plan onayı", short: "Plan", description: "Plan çıktısı onay kutusuna düşer; düzenleyebilir, onaylayabilir ya da notla reddedebilirsin." },
  boundary_check: { label: "Sınır denetimi", short: "Sınır", description: "Diff ve komut kaydı sınırlarla otomatik karşılaştırılır." },
  build_test: { label: "Build/test kanıtı", short: "Build/test", description: "Repo'daki lint, typecheck, test ve build komutlarını studiod çalıştırır." },
  cross_review: { label: "Çapraz inceleme", short: "İnceleme", description: "Farklı sağlayıcı inceler; engelleyici bulgu varsa iş yazara döner." },
  user_final: { label: "Son onay", short: "Son onay", description: "Özet, diff ve kanıtlar tek ekranda gösterilir." },
  deploy_approval: { label: "Deploy onayı", short: "Deploy", description: "Deploy düğümünden önce çalışır. Production için kilitlidir." },
  custom_command: { label: "Özel komut", short: "Komut", description: "Verdiğin komut 0 koduyla bitmelidir." },
};

export const conditionStrings: Record<EdgeCondition, { label: string; description: string }> = {
  default: { label: "Varsayılan", description: "Düğüm başarıyla bitince" },
  passed: { label: "Geçti", description: "Kapı ya da adım geçince" },
  failed: { label: "Başarısız", description: "Başarısız olursa (geri dönebilir)" },
  true: { label: "Doğru", description: "Koşul doğruysa" },
  false: { label: "Yanlış", description: "Koşul yanlışsa (geri dönebilir)" },
  approved: { label: "Onaylandı", description: "Onay verilince" },
  rejected: { label: "Reddedildi", description: "Reddedilirse (geri dönebilir)" },
};

export const outputFormatStrings: Record<AgentOutputFormat, string> = {
  text: "Metin",
  plan: "Plan",
  findings: "Bulgular",
  decision: "Karar",
};

export const synthesisFormatStrings: Record<SynthesisOutputFormat, string> = {
  decision: "Karar belgesi",
  report: "Rapor",
  text: "Metin",
};

export const mergeStrategyStrings: Record<MergeStrategy, string> = {
  merge: "Merge",
  squash: "Squash",
  cherry_pick: "Cherry-pick",
};

export const sandboxStrings: Record<SandboxLevel, string> = {
  read_only: "Salt okuma",
  workspace_write: "Çalışma alanı",
  full: "Tam erişim",
};

export const remoteAccessStrings: Record<RemoteAccess, string> = {
  none: "Yok",
  read: "Salt okuma",
  limited: "Sınırlı yazma",
  full: "Tam yetki",
};

export const onExhaustedStrings: Record<OnExhausted, { label: string; description: string }> = {
  switch_provider: { label: "Diğer sağlayıcıya geç", description: "Eşdeğer rol için diğer sağlayıcı devralır." },
  queue: { label: "Kuyrukta beklet", description: "Limit sıfırlanınca kaldığı yerden devam eder." },
  ask: { label: "Bana sor", description: "Onay kutusuna bir karar düşer." },
};

export const modeLabels: Record<FlowMode, string> = {
  single: "Tek",
  duo: "İkili",
  race: "Yarış",
  pipeline: "Hat",
  council: "Kurul",
  team: "Ekip",
  custom: "Özel",
};

export const severityStrings: Record<string, string> = {
  critical: "Kritik",
  high: "Yüksek",
  medium: "Orta",
  low: "Düşük",
};

const DIRECTIONS: Record<string, string> = { up: "yukarı", down: "aşağı", left: "sola", right: "sağa" };

/** Turkish screen-reader strings for the canvas (@xyflow/react ariaLabelConfig). */
export const canvasAria = {
  "node.a11yDescription.default": "Seçmek için Enter ya da boşluk tuşuna bas. Silmek için Delete, vazgeçmek için Escape.",
  "node.a11yDescription.keyboardDisabled":
    "Seçmek için Enter ya da boşluk tuşuna bas. Sonra ok tuşlarıyla düğümü taşıyabilirsin. Silmek için Delete, vazgeçmek için Escape.",
  "node.a11yDescription.ariaLiveMessage": ({ direction, x, y }: { direction: string; x: number; y: number }) =>
    `Seçili düğüm ${DIRECTIONS[direction] ?? direction} taşındı. Yeni konum: x ${x}, y ${y}`,
  "edge.a11yDescription.default": "Bağlantıyı seçmek için Enter ya da boşluk tuşuna bas. Silmek için Delete, vazgeçmek için Escape.",
  "controls.ariaLabel": "Tuval denetimleri",
  "controls.zoomIn.ariaLabel": "Yakınlaştır",
  "controls.zoomOut.ariaLabel": "Uzaklaştır",
  "controls.fitView.ariaLabel": "Tümünü göster",
  "controls.interactive.ariaLabel": "Etkileşimi aç/kapat",
  "minimap.ariaLabel": "Mini harita",
  "handle.ariaLabel": "Bağlantı noktası",
};

export const s = {
  pageTitle: "Akışlar",
  pageSubtitle: "Ajanları, kapıları ve dalları tuvalde birleştir. Modlar ve stüdyolar da birer akıştır.",
  newFlow: "Yeni akış",
  schedulesLink: "Zamanlamalar",
  savedFlows: "Kayıtlı akışlar",
  modeTemplates: "Mod şablonları",
  modeTemplatesHint: "Hazır bir moddan başla, tuvalde dilediğin gibi değiştir.",
  blankFlow: "Boş akış",
  blankFlowHint: "Tuvale sıfırdan düğüm ekle.",
  template: "Şablon",
  nodeCount: (n: number) => `${n} düğüm`,
  version: (v: number) => `v${v}`,
  updated: (rel: string) => `güncellendi ${rel}`,
  noWorkspace: "Önce bir çalışma alanı seç.",
  emptyFlowsTitle: "Henüz kayıtlı akış yok",
  emptyFlowsBody: "Bir mod şablonundan başla ya da boş bir tuval aç.",
  loadError: "Akışlar yüklenemedi",
  modesError: "Mod şablonları yüklenemedi",
  retry: "Tekrar dene",
  open: "Aç",
  duplicate: "Kopyasını oluştur",
  delete: "Sil",
  copySuffix: " (kopya)",
  duplicated: "Kopya oluşturuldu",
  deleted: "Akış silindi",
  deleteTitle: (name: string) => `"${name}" silinsin mi?`,
  deleteBody: "Akışın tüm sürümleri silinir. Bu akışla başlamış görevler etkilenmez.",
  cancel: "Vazgeç",
  more: "Diğer",
  searchFlows: "Akışlarda ara",
  noMatches: "Eşleşen akış yok.",

  editor: {
    untitled: "Adsız akış",
    back: "Akışlar",
    nameLabel: "Akış adı",
    unsaved: "Kaydedilmedi",
    saved: "Kaydedildi",
    save: "Kaydet",
    saving: "Kaydediliyor…",
    saveFailed: "Kaydedilemedi",
    savedWithErrors: (n: number) => `Kaydedildi · ${n} hata var. Görev başlatmadan önce düzelt.`,
    validate: "Doğrula",
    validating: "Doğrulanıyor…",
    valid: "Akış geçerli",
    validFlow: "Geçerli",
    errorsCount: (n: number) => `${n} hata`,
    warningsCount: (n: number) => `${n} uyarı`,
    validationFailed: "Doğrulama yapılamadı",
    issues: "Doğrulama sonuçları",
    noIssues: "Hata ya da uyarı yok.",
    staleIssues: "Değişiklikler var; sonuçlar güncellenecek.",
    flowIssue: "Akış",
    undo: "Geri al",
    redo: "Yinele",
    autoLayout: "Otomatik yerleşim",
    fitView: "Tümünü göster",
    zoomIn: "Yakınlaştır",
    zoomOut: "Uzaklaştır",
    minimap: "Mini harita",
    settings: "Akış ayarları",
    versions: "Sürüm geçmişi",
    startTask: "Bu akışla görev başlat",
    startTaskShort: "Görev başlat",
    notValidated: "Doğrulanmadı",
    more: "Diğer eylemler",
    startFrom: "Şablondan başla",
    duplicateSel: "Çoğalt",
    copy: "Kopyala",
    paste: "Yapıştır",
    deleteSel: "Sil",
    selectAll: "Tümünü seç",
    loadFailed: "Akış açılamadı",
    templateFailed: "Şablon yüklenemedi",
    notFound: "Akış bulunamadı",
    notFoundBody: "Silinmiş ya da başka bir çalışma alanına ait olabilir.",
    backToList: "Akışlara dön",
    leaveTitle: "Kaydedilmemiş değişiklikler var",
    leaveBody: "Bu sayfadan çıkarsan son değişiklikler kaybolur.",
    leave: "Değişiklikleri at",
    stay: "Sayfada kal",
    copied: (n: number) => `${n} düğüm kopyalandı`,
    pasted: (n: number) => `${n} düğüm yapıştırıldı`,
    emptyCanvasTitle: "Tuval boş",
    emptyCanvasBody: "Soldaki listeden bir düğüm sürükle ya da çift tıkla.",
    connectHint: "Bağlantının koşulunu seç",
    canvasLabel: "Akış tuvali",
    readOnlyBanner: (v: number) => `v${v} görüntüleniyor · salt okunur`,
    restore: "Bu sürümü geri yükle",
    restoreDone: (from: number, to: number) => `v${from} geri yüklendi · yeni sürüm v${to}`,
    exitPreview: "Güncel sürüme dön",
    replaceTitle: "Tuvaldeki akış değiştirilsin mi?",
    replaceBody: "Kaydedilmemiş değişiklikler kaybolacak. Kaydedilmiş sürümler etkilenmez.",
    replace: "Değiştir",
    shortcuts: "Kısayollar",
    flowFromMode: (label: string) => `${label} akışı`,
    restoreConfirmTitle: (v: number) => `v${v} geri yüklensin mi?`,
    restoreConfirmBody: "Bu sürüm yeni bir sürüm olarak kaydedilir; kaydedilmemiş değişiklikler kaybolur.",
    previewHint: "Değiştirmek için güncel sürüme dön ya da bu sürümü geri yükle.",
    paletteGroup: "Akış düzenleyici",
    addNodeCommand: (label: string) => `Düğüm ekle: ${label}`,
  },

  chooser: {
    title: "Nereden başlayalım?",
    subtitle: "Bir mod şablonu, stüdyo ya da boş tuval seç. Sonra her şeyi değiştirebilirsin.",
    modes: "Modlar",
    studios: "Stüdyolar",
    blank: "Boş tuval",
    loading: "Şablonlar yükleniyor…",
    studiosError: "Stüdyolar yüklenemedi",
    nodes: (n: number) => `${n} düğüm`,
  },

  palette: {
    title: "Düğümler",
    hint: "Sürükle ya da çift tıkla",
    search: "Düğüm ara",
    groups: { agents: "Ajanlar", control: "Akış denetimi", branching: "Dallanma", delivery: "Teslim" },
    added: (label: string) => `${label} eklendi`,
    collapse: "Düğüm listesini gizle",
    expand: "Düğüm listesini göster",
  },

  inspector: {
    close: "Kapat",
    node: "Düğüm",
    edge: "Bağlantı",
    multi: (n: number) => `${n} öğe seçili`,
    multiHint: "Birden fazla öğe seçili. Çoğaltabilir, kopyalayabilir ya da silebilirsin.",
    label: "Etiket",
    id: "Kimlik",
    idHint: "Şablonlarda nodes.<kimlik> olarak kullanılır.",
    idInvalid: "Harf ya da _ ile başlamalı; yalnız harf, rakam ve _ içermeli.",
    idTaken: "Bu kimlik başka bir düğümde kullanılıyor.",
    general: "Genel",
    model: "Model",
    prompt: "Prompt şablonu",
    promptHint: "{{ yazınca değişkenler önerilir. ⌃Space ile listeyi aç.",
    behavior: "Davranış",
    advanced: "Gelişmiş",
    issues: "Sorunlar",
    profile: "Profil",
    noProfile: "Profil yok · elle ayarla",
    profileHint: "Profil seçilirse sağlayıcı, model, rol ve sınırlar profilden gelir.",
    profilesError: "Profiller yüklenemedi",
    provider: "Sağlayıcı",
    providerDefault: "Varsayılan",
    modelLabel: "Model",
    modelPlaceholder: "CLI varsayılanı",
    effort: "Efor",
    effortDefault: "Varsayılan",
    role: "Rol",
    outputFormat: "Çıktı biçimi",
    writes: "Kod yazar",
    writesHint: "Kapalıysa salt okuma çalışır, worktree açılmaz.",
    repos: "Hedef repolar",
    allRepos: "Görevin hedeflediği tüm repolar",
    pickRepos: "Yalnız seçilenler",
    reposEmpty: "Bu çalışma alanında repo yok.",
    reposError: "Repolar yüklenemedi",
    maxTurns: "En fazla tur",
    unlimited: "Sınırsız",
    tools: "Studio araçları",
    allTools: "Tüm uygun araçlar",
    pickTools: "Yalnız seçilenler",
    toolsError: "Araç listesi yüklenemedi",
    boundaries: "Düğüme özel sınırlar",
    boundariesHint: "Çalışma alanı ve profil sınırlarıyla birleşir; en kısıtlayıcı olan geçerlidir.",
    forbiddenPaths: "Yasak yollar",
    readonlyPaths: "Salt okunur yollar",
    allowedCommands: "İzinli komutlar",
    deniedCommands: "Yasak komutlar",
    pathPlaceholder: "örn. infra/**",
    commandPlaceholder: "örn. pnpm test*",
    network: "Ağ erişimi",
    sandbox: "Sandbox",
    remoteAccess: "Uzak erişim",
    perspective: "Bakış açısı",
    perspectivePlaceholder: "örn. güvenlik odaklı, karşı tez",
    webAccess: "Web erişimi",
    webAccessHint: "Araştırma için web'e çıkabilir.",
    gateKind: "Kapı türü",
    gateLocked: "Production hedeflerinde kilitli; kapatılamaz.",
    commands: "Çalışacak komutlar",
    commandsAll: "Repo'da tanımlı tüm komutlar",
    commandsPick: "Yalnız seçilenler",
    command: "Komut",
    commandPlaceholderGate: "örn. pnpm e2e",
    review: "İnceleme",
    reviewer: "İnceleyen profil",
    reviewerDefault: "Diğer sağlayıcının varsayılanı",
    reviewerModel: "İnceleyen model",
    reviewFocus: "İnceleme odağı",
    reviewFocusPlaceholder: "örn. güvenlik ve hata yönetimi",
    targetNode: "Denetlenen düğüm",
    targetDefault: "Önceki düğüm (varsayılan)",
    maxRounds: "Tur sınırı",
    maxRoundsHint: "Başarısız bağlantısıyla en fazla bu kadar geri döner.",
    blocking: "Engelleyici önem dereceleri",
    sameProviderWarn: "İnceleyen, yazarla aynı sağlayıcıda olamaz.",
    joinMode: "Bekleme",
    joinAll: "Hepsini bekle",
    joinAny: "İlk biteni bekle",
    judge: "Kim seçer?",
    judgeUser: "Ben",
    judgeAgent: "Hakem ajan",
    judgeProfile: "Hakem profili",
    criteria: "Ölçütler",
    runGates: "Her sonuçta çalışacak kapılar",
    expression: "Koşul ifadesi",
    expressionHint: "Jinja ifadesi. Doğruysa 'Doğru', değilse 'Yanlış' bağlantısı izlenir.",
    expressionPlaceholder: "nodes.review.data.findings | length == 0",
    maxLoops: "Döngü sınırı",
    devilAdvocate: "Önce karşı tez iste",
    devilAdvocateHint: "Sentezden önce görüşlere karşı tez yazdırılır.",
    proposeMemory: "Kararı hafızaya öner",
    proposeMemoryHint: "decisions/ katmanına onaylı öneri olarak düşer.",
    synthesisPromptHint: "Boş bırakılırsa yerleşik sentez talimatı kullanılır.",
    synthesisPlaceholder: "Görüşleri karşılaştır, karşı tezi dikkate al ve tek bir karar yaz…",
    bodyPlaceholder: "## Özet\n{{ nodes.dev.output | clip(2000) }}",
    targetRef: "Hedef branch",
    targetRefPlaceholder: "Repo'nun varsayılan branch'i",
    strategy: "Strateji",
    requireApproval: "Birleştirmeden önce onay iste",
    resolveConflicts: "Çakışmaları ajanla çöz",
    gitAction: "Eylem",
    gitPush: "Push",
    gitPr: "PR/MR aç",
    baseRef: "Taban branch",
    baseRefPlaceholder: "Varsayılan branch",
    draft: "Taslak olarak aç",
    titleTemplate: "Başlık şablonu",
    bodyTemplate: "Açıklama şablonu",
    bodyTemplateHint: "Boşsa görev özeti ve kanıtlar kullanılır.",
    pushBranch: "Push branch şablonu",
    pushBranchHint: "Boşsa worktree'nin kendi branch'i. PR düzeltmeleri için {{ input.push_branch }}.",
    watch: "PR'ı takip et",
    watchHint: "CI ve inceleme yorumları izlenir.",
    autofix: "Otomatik düzelt",
    autofixHint: "CI hatalarını ve yorumları ajan düzeltir.",
    deployProfile: "Deploy profili",
    deployProfilePlaceholder: "Profil seç",
    deployProfileManual: "Profil kimliği",
    deployMissing: "Deploy profilleri bu motorda henüz yok; kimliği elle girebilirsin.",
    deployEmpty: "Bu çalışma alanında deploy profili yok. Bağlantılar sayfasından ekleyebilirsin.",
    productionDeploy: "Production deploy'undan önce deploy onayı her zaman istenir.",
    instructions: "Talimat",
    instructionsPlaceholder: "Kullanıcıdan ne yapmasını ya da ne girmesini istiyorsun?",
    inputSchema: "Girdi şeması (JSON)",
    inputSchemaHint: "İsteğe bağlı JSON Schema; boşsa serbest metin istenir.",
    jsonInvalid: "Geçerli bir JSON nesnesi değil.",
    parallelInfo: "Bu düğümden çıkan tüm dallar aynı anda başlar. Dalları bir Birleşme, Karşılaştır ya da Sentez düğümünde topla.",
    edgeCondition: "Koşul",
    edgeFrom: "Kaynak",
    edgeTo: "Hedef",
    deleteEdge: "Bağlantıyı sil",
    deleteNode: "Düğümü sil",
    duplicateNode: "Çoğalt",
    loopEdge: "Geri dönen bağlantı: tur sınırı olan bir kapı ya da koşuldan çıkmalı.",
  },

  settings: {
    title: "Akış ayarları",
    description: "Açıklama",
    descriptionPlaceholder: "Bu akış ne işe yarar?",
    gates: "Kapılar",
    gatesHint: "Akıştaki bu tür kapılar açılıp kapatılabilir.",
    locked: "Kilitli",
    deployLockedNote: "Production deploy onayı her zaman çalışır ve kapatılamaz.",
    budget: "Bütçe",
    budgetHint: "Abonelikte dolar anlamsız; bütçe limit yüzdesiyle tanımlanır.",
    fiveHour: "5 saatlik pencere",
    weekly: "Haftalık pencere",
    duration: "En fazla süre",
    turns: "En fazla tur",
    percentSuffix: "%",
    minutesSuffix: "dk",
    limitPolicy: "Limit dolunca",
    parallel: "Aynı anda en fazla ajan",
    checkpoint: "Her düğümden sonra checkpoint",
    checkpointHint: "Worktree ve hafıza durumu her adımda kaydedilir; geri alınabilir.",
    inputs: "Girdiler (JSON)",
    inputsHint: "Görev girdilerinin tanımı; şablonlarda input.<ad> olarak önerilir.",
    template: "Şablon olarak işaretle",
    templateHint: "Akışlar listesinde şablon olarak görünür.",
  },

  versions: {
    title: "Sürüm geçmişi",
    current: "Güncel",
    view: "Görüntüle",
    restore: "Geri yükle",
    empty: "Henüz kaydedilmiş sürüm yok.",
    error: "Sürümler yüklenemedi",
    by: (who: string) => (who === "user" ? "sen" : who),
    unsavedFirst: "Sürüm geçmişi kaydettikten sonra oluşur.",
  },

  start: {
    title: "Bu akışla görev başlat",
    description: "Görev, kaydedilmiş akışın güncel sürümüyle çalışır.",
    taskTitle: "Başlık",
    taskTitlePlaceholder: "Boş bırakılırsa istemden üretilir",
    prompt: "İstem",
    promptPlaceholder: "Ne yapılsın? Bu metin şablonlarda {{ input.prompt }} olarak kullanılır.",
    unsavedNote: "Kaydedilmemiş değişiklikler var; başlatmadan önce kaydedilecek.",
    submit: "Görevi başlat",
    submitSave: "Kaydet ve başlat",
    started: "Görev başlatıldı",
    open: "Görevi aç",
    failed: "Görev başlatılamadı",
  },

  schedules: {
    title: "Zamanlamalar",
    subtitle: "Akışları ya da modları düzenli aralıklarla görev olarak başlat.",
    back: "Akışlar",
    new: "Yeni zamanlama",
    edit: "Zamanlamayı düzenle",
    emptyTitle: "Henüz zamanlama yok",
    emptyBody: "Her sabah bağımlılık taraması ya da her cuma sürüm notu gibi tekrarlayan işleri zamanla.",
    loadError: "Zamanlamalar yüklenemedi",
    runNow: "Şimdi çalıştır",
    ran: "Görev oluşturuldu",
    runFailed: "Çalıştırılamadı",
    enabled: "Etkin",
    disabled: "Duraklatıldı",
    enable: "Etkinleştir",
    disable: "Duraklat",
    toggled: (on: boolean) => (on ? "Zamanlama etkin" : "Zamanlama duraklatıldı"),
    nextRun: "Sonraki",
    lastRun: "Son çalışma",
    never: "Hiç çalışmadı",
    noNext: "Planlanmış çalışma yok",
    deleteTitle: (name: string) => `"${name}" zamanlaması silinsin mi?`,
    deleteBody: "Zamanlama kaldırılır. Daha önce oluşturduğu görevler etkilenmez.",
    deleted: "Zamanlama silindi",
    saved: "Zamanlama kaydedildi",
    saveFailed: "Kaydedilemedi",
    name: "Ad",
    namePlaceholder: "örn. Sabah bağımlılık taraması",
    taskTitle: "Görev başlığı",
    taskTitlePlaceholder: "örn. Bağımlılıkları güncelle",
    prompt: "İstem",
    promptPlaceholder: "Her çalışmada ajana verilecek istem",
    runWith: "Çalıştırılacak akış",
    flow: "Kayıtlı akış",
    mode: "Mod",
    when: "Ne zaman?",
    timezone: "Saat dilimi",
    advanced: "Gelişmiş (cron)",
    cronLabel: "Cron ifadesi",
    cronHint: "dakika saat gün ay haftanın-günü",
    cronInvalid: "Cron ifadesi çözülemedi.",
    preview: "Sonraki 5 çalışma",
    previewEmpty: "Bu ifadeyle yakın zamanda çalışma yok.",
    every: "Her",
    at: "Saat",
    minuteOf: "Dakika",
    interval: "Aralık",
    days: "Günler",
    dayOfMonth: "Ayın günü",
    save: "Kaydet",
    create: "Oluştur",
    flowMissing: "Akış bulunamadı",
    modeLabel: (label: string) => `${label} modu`,
    presets: {
      hourly: "Saatlik",
      daily: "Günlük",
      weekdays: "Hafta içi",
      weekly: "Haftalık",
      monthly: "Aylık",
      custom: "Özel",
    },
    intervals: { "5": "5 dakikada bir", "15": "15 dakikada bir", "30": "30 dakikada bir", "60": "Saat başı" },
  },
};
