/** Turkish UI strings of the studios feature. */
export const studioStrings = {
  title: "Stüdyolar",
  subtitle: "Hazır ajan kadroları, akışları ve kapılarıyla paketlenmiş işler. Birini seçin, girdileri doldurun, çalıştırın.",
  builtinSection: "Yerleşik stüdyolar",
  customSection: "Kendi stüdyolarınız",
  customEmpty: "Henüz kendi stüdyonuz yok",
  customEmptyHint: "Bir şablondan başlayın; ajanları, akışı ve kapıları YAML ile düzenleyin.",
  newStudio: "Yeni stüdyo",
  builtin: "Yerleşik",
  custom: "Özel",
  modified: "Düzenlendi",
  version: (v: number) => `v${v}`,
  versionLong: (v: number) => `Sürüm ${v}`,
  team: "Kadro",
  gates: "Kapılar",
  noGates: "Kapı yok",
  agents: (n: number) => (n === 1 ? "1 ajan" : `${n} ajan`),
  steps: (n: number) => (n === 1 ? "1 adım" : `${n} adım`),
  inputs: (n: number) => (n === 1 ? "1 girdi" : `${n} girdi`),
  loadError: "Stüdyolar yüklenemedi",
  notFound: "Stüdyo bulunamadı",
  notFoundHint: "Bu stüdyo silinmiş ya da kimliği değişmiş olabilir.",
  back: "Stüdyolar",
  retry: "Tekrar dene",
  search: "Stüdyo ara",
  noMatch: "Aramayla eşleşen stüdyo yok",
  openStudio: "Stüdyoyu aç",

  // Detail page
  edit: "Düzenle",
  flow: "Akış",
  flowHint: "Ajanlar, kapılar ve devretmeler. Sürükleyerek gezinin.",
  fitAll: "Tümünü sığdır",
  readableSize: "Okunur boyut",
  teamTitle: "Kadro",
  gatesTitle: "Kapılar",
  output: "Çıktı",
  outputs: "Sonuçlar",
  outputsHint: "Bu stüdyoyla bu çalışma alanında çalıştırılan görevler.",
  outputsEmpty: "Henüz sonuç yok",
  outputsEmptyHint: "Stüdyoyu çalıştırdığınızda biten görevlerin belgeleri burada listelenir.",
  readOutput: "Belgeyi oku",
  openTask: "Göreve git",
  copyAsNew: "Kopyasını oluştur",
  history: "Sürüm geçmişi",
  noWorkspace: "Çalışma alanı seçilmedi",
  noWorkspaceHint: "Stüdyoyu çalıştırmak için önce bir çalışma alanı oluşturun ya da seçin.",
  taskStatus: {
    draft: "Taslak",
    queued: "Kuyrukta",
    running: "Çalışıyor",
    waiting: "Bekliyor",
    completed: "Tamamlandı",
    failed: "Başarısız",
    cancelled: "İptal edildi",
  } as Record<string, string>,

  // Run form
  run: "Çalıştır",
  runHint: "Girdileri doldurun; önizlemede akışın sizin değerlerinizle nasıl kurulacağını görürsünüz.",
  taskTitle: "Görev başlığı",
  taskTitleHint: "Boş bırakılırsa ilk girdiden oluşturulur.",
  optional: "isteğe bağlı",
  preview: "Önizle",
  previewTitle: "Önizleme",
  previewHint: "Girdiler doğrulandı ve akış bu değerlerle kuruldu.",
  editInputs: "Girdileri düzenle",
  start: "Görevi başlat",
  starting: "Başlatılıyor…",
  created: "Görev oluşturuldu",
  createFailed: "Görev oluşturulamadı",
  instantiateFailed: "Önizleme oluşturulamadı",
  fixErrors: "Bazı alanlarda düzeltme gerekiyor.",
  required: (label: string) => `“${label}” alanı zorunlu.`,
  invalidChoice: (options: string[]) => `Geçersiz seçim. Seçenekler: ${options.join(", ")}.`,
  empty: "—",
  none: "Seçilmedi",
  selectRepo: "Repo seçin",
  selectBranch: "Branch seçin",
  selectHost: "Sunucu seçin",
  selectDb: "Veritabanı seçin",
  selectProfile: "Deploy profili seçin",
  selectFirstRepo: "Önce bir repo seçin",
  noRepos: "Bu çalışma alanında repo yok",
  noBranches: "Branch bulunamadı",
  noHosts: (env?: string) => (env ? `${env} ortamında sunucu yok` : "Kayıtlı sunucu yok"),
  noDbs: (env?: string) => (env ? `${env} ortamında veritabanı yok` : "Kayıtlı veritabanı yok"),
  noProfiles: (env?: string) => (env ? `${env} ortamında deploy profili yok` : "Deploy profili yok"),
  pickerUnavailable: "Liste alınamadı; değeri elle yazabilirsiniz.",
  manageConnections: "Bağlantıları yönet",
  onlyEnvironment: (env: string) => `Yalnız ${env} ortamı`,
  defaultBranch: "varsayılan",
  remoteBranches: "Uzak",
  localBranches: "Yerel",
  nodesBound: (n: number) => (n === 1 ? "1 düğüm hazır" : `${n} düğüm hazır`),
  shortcutHint: "⌘↵ ile gönderin",

  // Output reader
  outputTitle: "Stüdyo çıktısı",
  taskLabel: "Görev:",
  copyMarkdown: "Markdown olarak kopyala",
  copied: "Kopyalandı",
  exportMd: "Markdown indir",
  print: "Yazdır",
  readingTime: (min: number) => `${min} dk okuma`,
  words: (n: number) => `${new Intl.NumberFormat("tr-TR").format(n)} kelime`,
  toc: "İçindekiler",
  notFinished: "Görev henüz tamamlanmadı",
  notFinishedHint: "Belge, biten adımların çıktılarıyla kısmen oluşturuldu. Görev bittiğinde kendiliğinden güncellenir.",
  failedTask: "Görev başarısız oldu",
  failedTaskHint: "Belge, tamamlanan adımların çıktılarıyla oluşturuldu.",
  noOutput: "Bu görevin henüz çıktısı yok",
  noOutputHint: "Adımlar çıktı ürettikçe belge burada oluşur.",
  outputLoadError: "Çıktı yüklenemedi",
  templateFallback: "Çıktı şablonu işlenemedi; son adımın çıktısı gösteriliyor.",
  finishedAt: (when: string) => `Bitiş: ${when}`,
  startedAt: (when: string) => `Başlangıç: ${when}`,

  // Editor
  editorTitle: (name: string) => `${name} · Düzenleyici`,
  newEditorTitle: "Yeni stüdyo",
  save: "Kaydet",
  saving: "Kaydediliyor…",
  saveAsVersion: (v: number) => `Sürüm ${v} olarak kaydet`,
  createStudio: "Stüdyoyu oluştur",
  saved: (v: number) => `Sürüm ${v} kaydedildi`,
  createdStudio: "Stüdyo oluşturuldu",
  saveFailed: "Kaydedilemedi",
  noteLabel: "Sürüm notu",
  notePlaceholder: "Ne değişti? (isteğe bağlı)",
  saveDialogTitle: "Yeni sürümü kaydet",
  saveDialogDescription: (v: number) => `Sürümler hiçbir zaman üzerine yazılmaz; bu değişiklikler sürüm ${v} olarak saklanır.`,
  createDialogDescription: "Stüdyo ilk sürümüyle oluşturulur ve galeride görünür.",
  cancel: "Vazgeç",
  dirty: "Kaydedilmemiş değişiklikler",
  clean: "Kaydedildi",
  validation: "Doğrulama",
  graphPreview: "Akış",
  versions: "Sürümler",
  validating: "Doğrulanıyor…",
  valid: "Şablon geçerli",
  validHint: "Hata yok; kaydedebilirsiniz.",
  errors: (n: number) => (n === 1 ? "1 hata" : `${n} hata`),
  warnings: (n: number) => (n === 1 ? "1 uyarı" : `${n} uyarı`),
  line: (n: number) => `satır ${n}`,
  jumpToLine: "Satıra git",
  validationUnavailable: "Sunucu doğrulaması şu an yapılamıyor; yalnız YAML sözdizimi denetlendi.",
  parseBlocked: "YAML düzeltilene kadar sunucu doğrulaması bekliyor.",
  idChanged: "Stüdyo kimliği değiştirilemez. Farklı bir kimlikle kaydetmek için “Kopyasını oluştur”u kullanın.",
  idTaken: (id: string) => `“${id}” kimliği zaten kullanılıyor; başka bir kimlik seçin.`,
  leaveTitle: "Değişiklikler kaydedilmedi",
  leaveDescription: "Bu sayfadan ayrılırsanız kaydedilmemiş değişiklikler kaybolur.",
  leave: "Değişiklikleri at",
  stay: "Düzenlemeye dön",
  current: "Güncel",
  compareWith: "Karşılaştır",
  compareHint: "İki sürümü karşılaştırmak için birini seçin.",
  diffTitle: (a: number, b: number) => `Sürüm ${a} → Sürüm ${b}`,
  noDiff: "Bu iki sürüm arasında fark yok.",
  restore: "Bu sürüme dön",
  restoreTitle: (v: number) => `Sürüm ${v}'e dönülsün mü?`,
  restoreDescription: (v: number, next: number) =>
    `Sürüm ${v}'in içeriği yeni bir sürüm (${next}) olarak kaydedilir. Geçmiş silinmez.`,
  restoreNote: (v: number) => `Sürüm ${v}'e geri dönüldü`,
  restored: (v: number) => `Sürüm ${v}'e dönüldü`,
  loadIntoEditor: "Düzenleyiciye yükle",
  versionsEmpty: "Sürüm geçmişi yok",
  versionsLoadError: "Sürümler yüklenemedi",
  builtinOriginal: "Yerleşik özgün sürüm",
  editorHint: "YAML · ⌘S kaydet · Esc ile editörden çık",
  graphInvalid: "Akış önizlemesi için geçerli bir YAML gerekli.",

  // New studio dialog
  newDialogTitle: "Yeni stüdyo",
  newDialogDescription: "Bir şablon seçin; kadro, akış ve kapılar oradan kopyalanır. Sonra YAML düzenleyicide uyarlarsınız.",
  nameLabel: "Ad",
  namePlaceholder: "Örn. Güvenlik denetimi",
  idLabel: "Kimlik",
  idHint: "Küçük harf, rakam ve tire. Sonradan değiştirilemez.",
  templateLabel: "Şablon",
  blankTemplate: "Boş stüdyo",
  blankTemplateHint: "Tek ajanlı en sade akış",
  continue: "Düzenleyicide aç",
  badId: "Kimlik yalnız küçük harf, rakam ve tire içerebilir (2-63 karakter).",
  nameRequired: "Ad zorunlu.",

  // Palette
  commandNew: "Yeni stüdyo oluştur",
  commandOpen: (name: string) => `Stüdyo: ${name}`,
  commandEdit: "Stüdyoyu düzenle",
  commandRun: "Stüdyoyu çalıştır",
  commandGroup: "Stüdyolar",
} as const;

export const nodeKindLabels: Record<string, string> = {
  agent: "Ajan",
  advisor: "Danışman",
  gate: "Kapı",
  parallel: "Dallanma",
  join: "Birleşme",
  compare: "Karşılaştırma",
  condition: "Koşul",
  synthesis: "Sentez",
  merge: "Birleştirme",
  git: "Git",
  deploy: "Deploy",
  human: "İnsan",
};

export const gateLabels: Record<string, string> = {
  plan_approval: "Plan onayı",
  boundary_check: "Sınır denetimi",
  build_test: "Build/test kanıtı",
  cross_review: "Çapraz inceleme",
  user_final: "Son onay",
  deploy_approval: "Deploy onayı",
  custom_command: "Özel komut",
};

export const gateDescriptions: Record<string, string> = {
  plan_approval: "Uygulamaya geçmeden önce planı siz onaylarsınız.",
  boundary_check: "Değişikliklerin hafızadaki sınırlara uyduğunu studiod denetler.",
  build_test: "Build ve testleri studiod kendisi çalıştırır; kanıt saklanır.",
  cross_review: "Diğer model bağımsız inceler; engelleyici bulgu varsa iş geri döner.",
  user_final: "Sonuç ancak sizin onayınızla kabul edilir.",
  deploy_approval: "Deploy öncesi onay. Production için kilitli, kapatılamaz.",
  custom_command: "Tanımlı komut başarıyla (çıkış kodu 0) bitmeli.",
};

export const roleLabels: Record<string, string> = {
  writer: "Yazar",
  advisor: "Danışman",
  reviewer: "İnceleyen",
  planner: "Planlayıcı",
  tester: "Test eden",
  judge: "Hakem",
  synthesizer: "Sentezci",
};

export const edgeConditionLabels: Record<string, string> = {
  passed: "geçerse",
  failed: "kalırsa",
  true: "evet",
  false: "hayır",
  approved: "onaylanırsa",
  rejected: "reddedilirse",
};

export const environmentLabels: Record<string, string> = { local: "Yerel", test: "Test", production: "Production" };
