/** Turkish strings for task lists (also used by the home screen's task rows). */
import type { FlowMode, TaskSource, TaskStatus } from "./types";

export const taskStrings = {
  title: "Görevler",
  subtitle: (n: number) => (n === 1 ? "1 görev" : `${n} görev`),
  newTask: "Yeni görev",
  schedules: "Zamanlamalar",
  schedulesHint: "Zamanlanmış görev şablonları",
  views: { list: "Liste", queue: "Kuyruk" },
  viewsLabel: "Görünüm",
  status: {
    draft: "Taslak",
    queued: "Kuyrukta",
    running: "Çalışıyor",
    waiting: "Seni bekliyor",
    completed: "Tamamlandı",
    failed: "Başarısız",
    cancelled: "İptal edildi",
  } satisfies Record<TaskStatus, string>,
  modes: {
    single: "Tek",
    duo: "İkili",
    race: "Yarış",
    pipeline: "Hat",
    council: "Kurul",
    custom: "Özel",
  } satisfies Record<FlowMode, string>,
  sources: {
    user: "Kullanıcı",
    schedule: "Zamanlama",
    pr_watch: "PR takibi",
    issue: "Issue",
    studio: "Stüdyo",
  } satisfies Record<TaskSource, string>,
  savedFlow: "Kayıtlı akış",
  quality: "Kalite",
  qualityScore: (n: number) => `Kalite puanı ${Math.round(n)}`,
  filters: {
    label: "Filtreler",
    search: "Görevlerde ara",
    status: "Durum",
    mode: "Mod",
    source: "Kaynak",
    all: "Tümü",
    allStatuses: "Tüm durumlar",
    statusCount: (n: number) => `${n} durum`,
    clear: "Filtreleri temizle",
  },
  days: {
    today: "Bugün",
    yesterday: "Dün",
  },
  select: {
    row: (title: string) => `Seç: ${title}`,
    all: "Tümünü seç",
    count: (n: number) => (n === 1 ? "1 görev seçildi" : `${n} görev seçildi`),
    selectedSuffix: "görev seçildi",
    clear: "Seçimi temizle",
    cancel: "İptal et",
    cancelHint: "Yalnız kuyruktaki ve çalışan görevler iptal edilir",
    cancelled: (n: number) => (n === 1 ? "1 görev iptal edildi" : `${n} görev iptal edildi`),
    cancelFailed: (n: number) => (n === 1 ? "1 görev iptal edilemedi" : `${n} görev iptal edilemedi`),
    nothingToCancel: "Seçilenlerin hiçbiri iptal edilebilir durumda değil",
  },
  row: {
    open: (title: string) => `Aç: ${title}`,
    repos: (n: number) => (n === 1 ? "1 repo" : `${n} repo`),
  },
  empty: {
    title: "Henüz görev yok",
    description: "Ana sayfadaki görev alanından ilk görevini başlat; burada canlı olarak izlersin.",
    action: "İlk görevi başlat",
    filteredTitle: "Bu filtrelere uyan görev yok",
    filteredDescription: "Aramayı ya da filtreleri değiştirerek tekrar dene.",
  },
  error: {
    title: "Görevler yüklenemedi",
    missing: "Görev motoru henüz hazır değil. studiod güncellendiğinde görevler burada görünür.",
    retry: "Tekrar dene",
  },
  loadMore: "Daha fazla yükleniyor…",
  queue: {
    title: "Kuyruk",
    description: "Sırası gelen görev, sağlayıcı limitleri ve eşzamanlılık sınırı uygun olunca başlar.",
    empty: "Kuyruk boş",
    emptyDescription: "Bekleyen görev yok; yeni görevler hemen başlar.",
    position: (n: number) => `${n}. sırada`,
    priority: (n: number) => (n > 0 ? `Öncelik +${n}` : n < 0 ? `Öncelik ${n}` : "Normal öncelik"),
    holdUntil: (rel: string) => `${rel} sonra başlayacak`,
    cancel: "Kuyruktan çıkar",
    cancelled: "Görev kuyruktan çıkarıldı",
    error: "Kuyruk yüklenemedi",
  },
  cancelOne: "Görevi iptal et",
  cancelFailed: "Görev iptal edilemedi",
  commands: {
    queue: "Görev kuyruğu",
    schedules: "Zamanlanmış görevler",
    recentGroup: "Son görevler",
    openTask: (title: string) => `Görev: ${title}`,
  },
} as const;
