/** Turkish strings of the teams feature (list, builder, live view, composer and flow integration). */
import type { AssignmentStatus, IndependentTrigger, ReportMode, TeamMemberStatus, TeamMergeStrategy, TeamRole, TestMode } from "./types";

export const roleStrings: Record<TeamRole, { label: string; plural: string; description: string }> = {
  advisor: { label: "Danışman", plural: "danışman", description: "Kod yazmaz; rapor alır, danışma sorularını yanıtlar." },
  lead: { label: "Lider", plural: "lider", description: "Görevi alır, işi altındakilere böler, sonuçları birleştirir." },
  worker: { label: "Üye", plural: "üye", description: "Verilen işi yapar; altında üye varsa işi onlara da dağıtır." },
  tester: { label: "Test ajanı", plural: "test", description: "Bir üyenin çıktısını ya da birleştirilmiş işi test eder." },
};

export const testModeStrings: Record<TestMode, { label: string; description: string }> = {
  dependent: { label: "Bağımlı", description: "Bir üyenin her işinden sonra çalışır; başarısızlık o üyeye düzeltme olarak döner." },
  independent: { label: "Bağımsız", description: "Üstündeki üyenin birleştirilmiş çalışmasını test eder." },
};

export const reportModeStrings: Record<ReportMode, { label: string; description: string }> = {
  on_demand: { label: "Sorulunca", description: "Danışmana yalnız bir üye soru sorduğunda gidilir." },
  each_assignment: { label: "Her iş sonrası", description: "Her iş bitince danışmana rapor gider." },
  periodic: { label: "Periyodik", description: "Belirli aralıklarla danışmana rapor gider." },
};

export const triggerStrings: Record<IndependentTrigger, string> = {
  after_each_merge: "Her birleştirmede",
  at_end: "En sonda",
};

export const mergeStrings: Record<TeamMergeStrategy, string> = {
  merge: "Merge",
  squash: "Squash",
};

export const memberStatusStrings: Record<TeamMemberStatus, string> = {
  idle: "Boşta",
  working: "Çalışıyor",
  waiting: "Bekliyor",
  testing: "Test ediliyor",
  consulting: "Danışıyor",
  done: "Bitti",
  error: "Hata",
};

export const assignmentStatusStrings: Record<AssignmentStatus, string> = {
  pending: "Sırada",
  blocked: "Bağımlılık bekliyor",
  running: "Çalışıyor",
  testing: "Test ediliyor",
  completed: "Tamamlandı",
  failed: "Başarısız",
  cancelled: "İptal edildi",
};

export const effortLabels: Record<string, { label: string; short: string }> = {
  minimal: { label: "En az", short: "En az" },
  low: { label: "Düşük", short: "Düşük" },
  medium: { label: "Orta", short: "Orta" },
  high: { label: "Yüksek", short: "Yüksek" },
  xhigh: { label: "Çok yüksek", short: "Çok y." },
  max: { label: "En yüksek", short: "En y." },
};

export const s = {
  pageTitle: "Ekipler",
  pageSubtitle: "Danışman, lider, üyeler ve test ajanlarından bir ekip kur; görevi ekibe ver, çalışmayı canlı izle.",
  newTeam: "Yeni ekip",
  builtinTemplates: "Hazır şablonlar",
  builtinHint: "Bir şablondan başla, kurucuda dilediğin gibi değiştir.",
  savedTeams: "Kayıtlı ekipler",
  template: "Şablon",
  builtin: "Hazır",
  version: (v: number) => `v${v}`,
  updated: (rel: string) => `güncellendi ${rel}`,
  noWorkspace: "Önce bir çalışma alanı seç.",
  emptyTitle: "Henüz kayıtlı ekip yok",
  emptyBody: "Hazır bir şablonu kopyala ya da sıfırdan bir ekip kur.",
  loadError: "Ekipler yüklenemedi",
  missingApi: "Ekip API'si bu motor sürümünde henüz yok.",
  retry: "Tekrar dene",
  open: "Aç",
  edit: "Düzenle",
  duplicate: "Kopyasını oluştur",
  delete: "Sil",
  copySuffix: " (kopya)",
  duplicated: "Kopya oluşturuldu",
  deleted: "Ekip silindi",
  deleteTitle: (name: string) => `"${name}" silinsin mi?`,
  deleteBody: "Ekibin tüm sürümleri silinir. Bu ekiple başlamış görevler etkilenmez.",
  cancel: "Vazgeç",
  more: "Diğer işlemler",
  searchTeams: "Ekip ara",
  noMatches: "Aramana uyan ekip yok.",
  startWithTeam: "Bu ekiple görev başlat",
  startWithTeamNamed: (name: string) => `Bu ekiple görev başlat: ${name}`,
  members: (n: number) => `${n} üye`,
  preview: (name: string) => `${name} ekip şeması`,

  summary: {
    advisors: (n: number) => `${n} danışman`,
    leads: (n: number) => `${n} lider`,
    workers: (n: number) => `${n} üye`,
    testers: (n: number) => `${n} test`,
    provider: (name: string, n: number) => `${name} ×${n}`,
    label: "Ekip özeti",
  },

  start: {
    title: "Bu ekiple görev başlat",
    description: "Lider görevi alır, işi ekibe dağıtır. Sonra akışın kapıları çalışır.",
    prompt: "Görev",
    promptPlaceholder: "Ne yapılmasını istiyorsun? Hedefi, kısıtları ve bitti sayılma koşulunu yaz…",
    taskTitle: "Başlık",
    taskTitlePlaceholder: "Görevden türetilir",
    submit: "Başlat",
    started: "Görev başlatıldı",
    openTask: "Görevi aç",
    failed: "Görev başlatılamadı",
    unsavedNote: "Kaydedilmemiş değişiklikler satır içi ekip olarak gönderilir.",
  },

  builder: {
    untitled: "Adsız ekip",
    nameLabel: "Ekip adı",
    description: "Açıklama",
    descriptionPlaceholder: "Bu ekip ne için? (isteğe bağlı)",
    backToList: "Ekiplere dön",
    canvasLabel: "Ekip şeması",
    save: "Kaydet",
    saveCopy: "Kopya olarak kaydet",
    saving: "Kaydediliyor…",
    saved: "Kaydedildi",
    unsaved: "Kaydedilmedi",
    savedToast: (v: number) => `Ekip kaydedildi · v${v}`,
    createdToast: "Ekip oluşturuldu",
    saveFailed: "Ekip kaydedilemedi",
    loadFailed: "Ekip yüklenemedi",
    notFound: "Ekip bulunamadı",
    notFoundBody: "Silinmiş ya da başka bir çalışma alanına ait olabilir.",
    builtinBanner: "Hazır şablon · değişiklikler kopya olarak kaydedilir",
    undo: "Geri al",
    redo: "Yinele",
    fitView: "Tümünü göster",
    zoomIn: "Yakınlaştır",
    zoomOut: "Uzaklaştır",
    settings: "Ekip ayarları",
    shortcuts: "Kısayollar",
    addChild: "Alt ajan ekle",
    addWorker: "Üye ekle",
    addDependentTester: "Bağımlı test ajanı ekle",
    addIndependentTester: "Bağımsız test ajanı ekle",
    addAdvisor: "Danışman ekle",
    removeAdvisor: "Danışmanı kaldır",
    addMenu: (name: string) => `${name} için ekle`,
    duplicateSubtree: "Alt ağacı çoğalt",
    deleteMember: "Sil",
    deleteTitle: (name: string, n: number) => (n > 1 ? `"${name}" ve altındaki ${n - 1} ajan silinsin mi?` : `"${name}" silinsin mi?`),
    deleteBody: "Bu ajanların ayarları ve bağlı test ajanları da kaldırılır. Geri alabilirsin.",
    leadLocked: "Lider silinemez ya da taşınamaz.",
    fromTemplate: "Şablondan başla",
    fromTemplateHint: "Mevcut şema değiştirilir; geri alabilirsin.",
    templatesEmpty: "Hazır şablon yok.",
    emptyHint: "Liderin altındaki + düğmesiyle üye ekle",
    dropHere: (name: string) => `${name} altına taşı`,
    dropInvalid: "Buraya taşınamaz",
    moved: (name: string, to: string) => `${name}, ${to} altına taşındı`,
    readOnlyVersion: (v: number) => `v${v} görüntüleniyor · salt okuma`,
    exitPreview: "Güncel sürüme dön",
    restore: "Bu sürüme dön",
    restoreDone: (from: number, to: number) => `v${from} geri yüklendi · yeni sürüm v${to}`,
    versions: "Sürümler",
    versionsEmpty: "Henüz sürüm yok.",
    current: "güncel",
    validate: "Denetle",
    validTeam: "Ekip geçerli",
    notValidated: "Denetlenmedi",
    errorsCount: (n: number) => `${n} hata`,
    warningsCount: (n: number) => `${n} uyarı`,
    issues: "Sorunlar",
    noIssues: "Sorun bulunamadı.",
    teamIssue: "Ekip geneli",
    apply: "Uygula",
    applyHint: "Değişiklikler yalnız bu göreve uygulanır.",
    saveAsTeam: "Ekip olarak kaydet",
    customizeTitle: "Ekibi özelleştir",
    customizeDescription: "Bu görev için ekibi değiştir; şablon değişmez.",
    leaveTitle: "Kaydedilmemiş değişiklikler var",
    leaveBody: "Sayfadan çıkarsan ekipteki değişiklikler kaybolur.",
    leave: "Çık",
    stay: "Kal",
    keyboardHelp: [
      { keys: ["+"], label: "Alt ajan ekle" },
      { keys: ["T"], label: "Bağımlı test ajanı ekle" },
      { keys: ["↑", "↓", "←", "→"], label: "Şemada gezin" },
      { keys: ["⌘", "D"], label: "Alt ağacı çoğalt" },
      { keys: ["⌫"], label: "Sil" },
      { keys: ["⌘", "Z"], label: "Geri al" },
      { keys: ["⌘", "⇧", "Z"], label: "Yinele" },
      { keys: ["⌘", "S"], label: "Kaydet" },
    ] as const,
  },

  inspector: {
    close: "Kapat",
    general: "Genel",
    name: "Ad",
    id: "Kimlik",
    role: "Rol",
    model: "Model",
    provider: "Sağlayıcı",
    modelLabel: "Model",
    modelPlaceholder: "CLI varsayılanı",
    effort: "Efor",
    effortDefault: "Varsayılan",
    effortHint: "Daha yüksek efor daha derin düşünür, daha çok limit harcar.",
    profile: "Profil",
    noProfile: "Profil yok · elle ayarla",
    profileHint: "Profil model, efor ve talimatları devralır.",
    fromProfile: "Profilden",
    instructions: "Talimat",
    instructionsPlaceholder: "Bu ajanın rolünü ve sorumluluğunu anlat. Yöneticisi de bunu görür.",
    behavior: "Davranış",
    writes: "Yazabilir",
    writesHint: "Kapalıyken kendi worktree'si olmaz, salt okur.",
    advisorReadOnly: "Danışman her zaman salt okur.",
    boundaries: "Sınırlar",
    boundariesHint: "Bu ajana özel ek kısıtlar (çalışma alanı sınırlarına eklenir).",
    forbiddenPaths: "Yasak yollar",
    readonlyPaths: "Salt okunur yollar",
    allowedCommands: "İzinli komutlar",
    deniedCommands: "Yasak komutlar",
    pathPlaceholder: "infra/** · .env*",
    commandPlaceholder: "pnpm test",
    network: "Ağ erişimi",
    tester: "Test",
    testMode: "Mod",
    testTarget: "Test ettiği üye",
    testTargetPlaceholder: "Üye seç",
    testScope: "Kapsam",
    testCommand: "Test komutu",
    testCommandPlaceholder: "pnpm e2e",
    testCommandHint: "Test ajanının mutlaka çalıştırması gereken komut (isteğe bağlı).",
    advises: "Danıştığı üye",
    reportsTo: "Yöneticisi",
    issues: "Sorunlar",
  },

  settings: {
    title: "Ekip ayarları",
    reporting: "Danışmana rapor",
    reportMode: "Rapor biçimi",
    interval: "Aralık",
    minutes: "dk",
    limits: "Güvenlik sınırları",
    maxParallel: "En fazla eşzamanlı üye",
    maxDepth: "En fazla derinlik",
    maxDepthHint: "Lider 0. seviyedir.",
    maxAssignments: "En fazla iş",
    testing: "Test",
    testRounds: "Düzeltme turu",
    testRoundsHint: "Bağımlı test başarısızlığı üyeye en fazla bu kadar geri döner.",
    independentTrigger: "Bağımsız testler",
    merging: "Birleştirme",
    mergeStrategy: "Üye branch'i → yönetici branch'i",
  },

  live: {
    label: "Canlı ekip",
    title: "Canlı ekip görünümü",
    pageTitle: "Canlı ekip",
    openFull: "Tam sayfada aç",
    openTask: "Görevi aç",
    back: "Geri",
    loading: "Ekip yükleniyor",
    notStartedTitle: "Ekip henüz başlamadı",
    notStartedBody: "Lider görevi aldığında ekip burada canlanır.",
    notFoundTitle: "Bu koşuda ekip yok",
    notFoundBody: "Koşu bir ekip düğümü içermiyor ya da ekip API'si henüz yok.",
    errorTitle: "Ekip görünümü yüklenemedi",
    finished: "Ekip işi bitirdi",
    finishedFailed: "Ekip başarısız oldu",
    finishedCancelled: "Ekip iptal edildi",
    attempt: (n: number) => `${n}. deneme`,
    provider: "Sağlayıcı",
    switchedShort: (from: string) => `${from} yerine`,
    switched: (from: string, to: string) => `${from} limitte olduğu için ${to} ile çalışıyor`,
    limitWait: "Limit bekleniyor",
    limitWaitUntil: (time: string) => `Limit bekleniyor · ${time}`,
    delivered: {
      steer: (name: string) => `${name} çalışan turuna yönlendirildi`,
      queued: (name: string) => `${name} mesajı bir sonraki turunda alacak`,
      turn: (name: string) => `${name} mesaj için yeni bir tura başladı`,
      direct: (name: string) => `${name} oturumuna iletildi`,
    },
    kpiAssignments: "İş",
    kpiActive: "Etkin üye",
    kpiTests: "Test başarısı",
    kpiMerges: "Birleştirme",
    kpiConflicts: (n: number) => (n === 1 ? "1 çakışma" : `${n} çakışma`),
    kpiNoTests: "—",
    noAssignment: "İş bekliyor",
    advisorIdle: "Rapor bekliyor",
    testerIdle: "Test bekliyor",
    idleSince: "Boşta",
    doneCount: (n: number) => `${n} iş bitti`,
    tokens: "token",
    tokensIn: "giriş",
    tokensOut: "çıkış",
    context: "Bağlam",
    contextOf: (pct: number) => `bağlamın %${pct}'i dolu`,
    limitsShare: "Limit payı",
    teamShare: (pct: number) => `ekip token'larının %${pct}'i`,
    history: "İş geçmişi",
    historyEmpty: "Henüz iş almadı.",
    session: "Oturum",
    noSession: "Henüz oturum yok",
    openStream: "Canlı akışı aç",
    message: "Mesaj gönder",
    steer: "Yönlendir",
    messageHint: "Mesaj bir sonraki tura girer; yönlendirme çalışan tura hemen eklenir.",
    messagePlaceholder: (name: string) => `${name} için mesaj…`,
    steerPlaceholder: (name: string) => `${name} şu an ne yapmalı?`,
    send: "Gönder",
    sent: (name: string) => `${name} ajanına iletildi`,
    sendFailed: "Mesaj iletilemedi",
    report: "Rapor",
    advice: "Öneri",
    reportTo: (from: string, to: string) => `${from} → ${to}`,
    merge: "Birleştirme",
    conflicts: (n: number) => (n === 1 ? "1 çakışma" : `${n} çakışma`),
    conflictFiles: "Çakışan dosyalar",
    testPassed: "geçti",
    testFailed: "kaldı",
    testError: "hata",
    testRound: (n: number) => `tur ${n}`,
    timeline: "İş zaman çizelgesi",
    timelineEmpty: "Henüz iş dağıtılmadı.",
    from: (name: string) => `${name} verdi`,
    duration: "Süre",
    dependsOn: (n: number) => (n === 1 ? "1 işe bağlı" : `${n} işe bağlı`),
    focusMember: (name: string) => `${name} üyesine odaklan`,
    pickNode: "Ekip düğümü",
    statusAria: (name: string, status: string) => `${name}: ${status}`,
    engine: "Motor",
  },

  composer: {
    mode: "Ekip",
    modeHint: "Görevi bir ekip yapar: lider işi dağıtır, test ajanları doğrular.",
    picker: "Ekip",
    pickerSearch: "Ekip ara",
    pickerEmpty: "Ekip bulunamadı",
    pickerLoadFailed: "Ekipler yüklenemedi",
    choose: "Ekip seç",
    customize: "Özelleştir",
    customized: "Özelleştirildi",
    reset: "Şablona dön",
    noTeam: "Bir ekip seç",
    noTeams: "Henüz ekip yok",
    manage: "Ekipleri yönet",
    required: "Bir ekip seçin.",
    newTaskCommand: "Yeni görev: Ekip",
  },

  node: {
    label: "Ekip",
    description: "Ajanlardan oluşan bir ekip çalıştırır",
    long: "Lider görevi alır, işi ekibe böler; üyeler kendi worktree'lerinde çalışır, sonuçlar yukarı birleşir.",
    source: "Ekip kaynağı",
    fromTemplate: "Şablon",
    inline: "Satır içi",
    templatePick: "Ekip şablonu",
    templatePlaceholder: "Ekip seç",
    editInline: "Satır içi düzenle",
    editInlineHint: "Şablonu bu akışa özel bir kopyaya çevirir.",
    openTeam: "Ekipler sayfasında aç",
    noTeamSummary: "Ekip seçilmedi",
    inlineSummary: (n: number) => `Satır içi ekip · ${n} üye`,
    templateSummary: (name: string, n: number | null) => (n ? `${name} · ${n} üye` : name),
    prompt: "Liderin görevi",
    promptHint: "Lidere giden metin. Lider bunu ekibe böler.",
    teamsMissing: "Ekip listesi alınamadı; ekibi satır içi düzenleyebilirsin.",
  },

  commands: {
    newTeam: "Yeni ekip",
    teams: "Ekipler",
    builderGroup: "Ekip kurucu",
    addChild: "Seçili üyeye alt ajan ekle",
    settings: "Ekip ayarlarını aç",
  },
};
