/** Turkish strings for the sessions feature (list, live stream, discovery, new session). */
import { common } from "@/i18n/common";

export const sessionStrings = {
  title: "Oturumlar",
  description: "Ajan oturumlarını canlı izleyin, yönlendirin ve CLI'larda daha önce açılmış oturumları ekleyin.",
  tabs: { sessions: "Oturumlar", discover: "Mevcut oturumlar" },
  newSession: "Yeni oturum",
  openDrawer: "Çekmecede aç",
  back: "Oturumlar",
  loadError: "Oturumlar yüklenemedi",
  retry: common.retry,
  empty: {
    title: "Henüz oturum yok",
    description: "Yeni bir ajan oturumu başlatın ya da CLI'larda açtığınız oturumları ekleyin.",
    filtered: "Bu filtrelere uyan oturum yok",
    filteredHint: "Filtreleri temizleyip tekrar deneyin.",
    clear: "Filtreleri temizle",
  },
  sections: { active: "Etkin", recent: "Son oturumlar" },
  filters: {
    search: "Oturum ara",
    allProviders: "Tümü",
    allStates: "Tümü",
    active: "Etkin",
    finished: "Biten",
    allWorkspaces: "Tüm çalışma alanları",
    provider: "Sağlayıcı",
    state: "Durum",
    workspace: "Çalışma alanı",
  },
  origin: { created: "Oluşturuldu", imported: "Eklendi", external: "Harici" },
  location: { local: "Bu Mac", remote: "Uzak" },
  count: (n: number) => `${n} oturum`,
  health: {
    title: "CLI durumu",
    ok: (v: string | null) => (v ? `Hazır · ${v}` : "Hazır"),
    missing: "Kurulu değil",
    loggedOut: "Giriş yapılmamış",
    incompatible: "Sürüm test aralığı dışında",
    unknown: "Durum bilinmiyor",
  },
  // ---------------------------------------------------------------- stream
  stream: {
    label: "Oturum akışı",
    newFile: "yeni dosya",
    deletedFile: "silindi",
    statusRegion: "Oturum durumu",
    loading: "Oturum yükleniyor…",
    loadError: "Oturum geçmişi yüklenemedi",
    notFound: "Oturum bulunamadı",
    empty: "Henüz mesaj yok",
    emptyHint: "İlk mesajı gönderin; ajanın yanıtı burada canlı akar.",
    emptyReadonly: "Bu oturumda henüz olay yok.",
    newMessages: (n: number) => (n === 1 ? "1 yeni öğe" : `${n} yeni öğe`),
    jumpToEnd: "En sona git",
    you: "Siz",
    steer: "Yönlendirme",
    thinking: "Düşünce",
    thinkingLive: "Düşünüyor…",
    showThinking: "Düşünceyi göster",
    hideThinking: "Düşünceyi gizle",
    toolInput: "Girdi",
    toolOutput: "Çıktı",
    noOutput: "Çıktı yok",
    exit: (code: number) => `çıkış ${code}`,
    running: "Çalışıyor",
    failed: "Hata",
    truncated: "Çıktı kısaltıldı; tamamı motorda saklanıyor.",
    filesChanged: (n: number) => (n === 1 ? "1 dosya değişti" : `${n} dosya değişti`),
    change: { add: "eklendi", modify: "değişti", delete: "silindi", rename: "yeniden adlandırıldı" },
    turnDone: "Tur tamamlandı",
    turnError: "Tur hatayla bitti",
    turnInterrupted: "Tur durduruldu",
    turnMaxTurns: "Tur sınırına ulaşıldı",
    sessionStarted: "Oturum başladı",
    sessionResumed: "Oturum devam ettirildi",
    sessionImported: (n: number) => `Oturum içe aktarıldı · ${n} olay`,
    sessionEnded: { completed: "Oturum tamamlandı", closed: "Oturum kapatıldı", error: "Oturum hatayla bitti", killed: "Ajan süreci sonlandı" },
    stalled: (m: number) => `${m} dakikadır çıktı yok`,
    handoff: "Devretme",
    permission: {
      title: "İzin isteği",
      allowAuto: "Politika izin verdi",
      denyAuto: "Politika reddetti",
      allow: "İzin ver",
      deny: "Reddet",
      allowed: "İzin verildi",
      denied: "Reddedildi",
      waiting: "Onay bekleniyor",
      by: (who: string) => `karar: ${who}`,
      production: "Production: yalnız uygulamadan onaylanabilir",
      paths: "Dosyalar",
      policy: "Politika",
      notFound: "Onay kaydı aranıyor…",
      failed: "Karar kaydedilemedi",
    },
    usage: {
      tokens: "token",
      input: "giriş",
      output: "çıkış",
      context: "Bağlam",
      contextOf: (used: string, total: string) => `${used} / ${total}`,
    },
    composer: {
      placeholder: "Ajana bir mesaj yazın…",
      placeholderBusy: "Çalışan tura yönlendirme yazın…",
      placeholderEnded: "Mesaj gönderirseniz oturum kaldığı yerden devam eder…",
      readonly: "Bu oturum uygulama dışında çalışıyor; yalnız izlenebilir.",
      send: "Gönder",
      steer: "Yönlendir",
      interrupt: "Durdur",
      newline: "yeni satır",
      sent: "Mesaj gönderildi",
      steered: "Yönlendirme iletildi",
      interrupted: "Durdurma isteği gönderildi",
      failed: "İşlem başarısız",
    },
    actions: {
      close: "Oturumu kapat",
      closed: "Oturum kapatıldı",
      openPage: "Tam sayfada aç",
      replay: "Tekrar oynat",
      copyId: "Oturum kimliğini kopyala",
      more: "Diğer işlemler",
    },
    replay: {
      title: "Tekrar oynatma",
      play: "Oynat",
      pause: "Duraklat",
      restart: "Baştan başlat",
      speed: "Hız",
      position: "Konum",
      step: (i: number, n: number) => `${i} / ${n}`,
      empty: "Tekrar oynatılacak olay yok.",
    },
  },
  // ---------------------------------------------------------------- new session
  create: {
    title: "Yeni oturum",
    description: "Tek seferlik bir ajan oturumu başlatın. Görevden bağımsız çalışır.",
    provider: "Sağlayıcı",
    profile: "Profil",
    noProfile: "Profilsiz (varsayılanlar)",
    location: "Konum",
    localMac: "Bu Mac",
    repo: "Repo",
    noRepo: "Repo seçilmedi",
    cwd: "Çalışma dizini",
    cwdPlaceholder: "/Users/siz/src/proje",
    cwdRequired: "Çalışma dizini gerekli.",
    model: "Model",
    modelPlaceholder: "Profil veya CLI varsayılanı",
    prompt: "İlk mesaj",
    promptPlaceholder: "Ajandan ne istediğinizi yazın (isteğe bağlı)",
    submit: "Oturumu başlat",
    cancel: common.cancel,
    started: "Oturum başlatıldı",
    failed: "Oturum başlatılamadı",
    noWorkspace: "Önce bir çalışma alanı oluşturun.",
  },
  // ---------------------------------------------------------------- discovery
  discover: {
    title: "Mevcut oturumlar",
    description:
      "Bu Mac'te veya SSH hostlarında daha önce çalışmış Claude ve Codex oturumları. Ekleyince geçmişi aktarılır ve kaldığı yerden devam ettirilebilir.",
    location: "Konum",
    thisMac: "Bu Mac",
    cwdFilter: "Dizine göre süz",
    cwdPlaceholder: "Tüm dizinler",
    refresh: "Yenile",
    scanning: "Oturumlar taranıyor…",
    loadError: "Oturumlar taranamadı",
    empty: "Oturum bulunamadı",
    emptyHint: "Bu konumda CLI oturumu yok ya da CLI'lar kurulu değil.",
    hostsError: "SSH hostları okunamadı",
    import: "Ekle",
    imported: "Eklendi",
    open: "Aç",
    importing: "Ekleniyor…",
    importDone: "Oturum eklendi",
    importFailed: "Oturum eklenemedi",
    messages: (n: number) => `${n} mesaj`,
    running: "Çalışıyor",
    untitled: "Başlıksız oturum",
    group: (n: number) => (n === 1 ? "1 oturum" : `${n} oturum`),
    noWorkspace: "Oturum eklemek için bir çalışma alanı seçin.",
  },
} as const;

export type SessionStrings = typeof sessionStrings;
