/** Turkish strings for the menu bar popover and the quick palette window. */
export const windowStrings = {
  menubar: {
    limits: "Kullanım limitleri",
    limitsEmpty: "Henüz limit bilgisi yok",
    approvals: "Onay bekleyenler",
    approvalsEmpty: "Bekleyen onay yok",
    viewAll: (n: number) => `Tümünü gör (${n})`,
    openInApp: "Uygulamada aç",
    productionNote: "Production onayı yalnız uygulamadan verilir",
    agents: "Etkin ajanlar",
    agentsEmpty: "Etkin ajan yok",
    newTask: "Yeni görev",
    openApp: "AI Studio'yu aç",
    pause: "Bildirimleri duraklat",
    resume: "Bildirimleri sürdür",
    paused: "Bildirimler duraklatıldı · kritikler yine gelir",
    online: "Motor bağlı",
    offline: "Motor çalışmıyor",
    connecting: "Bağlanıyor…",
    resetIn: (t: string) => `${t} sonra`,
    resetUnknown: "bilinmiyor",
  },
  palette: {
    label: "Hızlı palet",
    placeholder: "Görev yazın ya da arayın…",
    newTask: "Yeni görev",
    newTaskWith: (q: string) => `Yeni görev: “${q}”`,
    newTaskHint: "Ana pencerede görev giriş alanını açar",
    creating: "Oluşturuluyor…",
    createFailed: "Görev oluşturulamadı",
    noWorkspace: "Önce bir çalışma alanı oluşturun",
    groups: { actions: "Eylemler", approvals: "Onaylar", tasks: "Son görevler", pages: "Sayfalar" },
    empty: "Sonuç yok",
    production: "Production",
    mode: "Mod",
    modes: { single: "Tek", duo: "İkili", race: "Yarış", pipeline: "Hat", council: "Kurul" },
    modeHints: {
      single: "Tek ajan çalışır",
      duo: "Biri yazar, diğer model inceler",
      race: "Aynı iş paralel yapılır, sonuçlar karşılaştırılır",
      pipeline: "Planlayıcı → geliştirici → inceleyen → test eden",
      council: "Kod yok: bağımsız görüşler ve tek karar belgesi",
    },
    hints: { navigate: "gezin", run: "aç", mode: "mod", close: "kapat" },
    taskStatus: { draft: "Taslak", queued: "Kuyrukta", running: "Çalışıyor", waiting: "Bekliyor", completed: "Tamamlandı", failed: "Başarısız", cancelled: "İptal" } as Record<string, string>,
  },
} as const;
