/** Turkish strings for the task composer (home screen) and its pickers. */
import type { BuiltinMode } from "../list/types";

export const createStrings = {
  composerLabel: "Yeni görev",
  titlePlaceholder: "Başlık (isteğe bağlı)",
  titleDerived: (t: string) => `Başlık: ${t}`,
  promptPlaceholder: "Ne yapılmasını istiyorsun? Hedefi, kısıtları ve bitti sayılma koşulunu yaz…",
  promptLabel: "Görev",
  submit: "Başlat",
  submitScheduled: "Zamanla",
  submitQueued: "Kuyruğa ekle",
  submitHint: "Başlatmak için ⌘↵",
  launching: "Başlatılıyor…",
  created: (title: string) => `“${title}” başlatıldı`,
  createdScheduled: (title: string) => `“${title}” zamanlandı`,
  failed: "Görev oluşturulamadı",
  mode: {
    label: "Çalışma modu",
    preview: "Akış önizlemesi",
    overriddenByStudio: "Stüdyo kendi akışını kullanır",
    overriddenByFlow: "Kayıtlı akış kullanılıyor",
    loading: "Akış yükleniyor",
    unavailable: "Akış önizlemesi alınamadı",
    loop: (n: number | null) => (n ? `başarısızsa geri döner · en fazla ${n} tur` : "başarısızsa geri döner"),
    labels: {
      single: "Tek",
      duo: "İkili",
      race: "Yarış",
      pipeline: "Hat",
      council: "Kurul",
    } satisfies Record<BuiltinMode, string>,
  },
  studio: {
    button: "Stüdyo",
    none: "Stüdyo yok",
    noneHint: "Serbest görev: modu sen seçersin",
    search: "Stüdyo ara",
    empty: "Stüdyo bulunamadı",
    clear: "Stüdyoyu kaldır",
    loadFailed: "Stüdyolar yüklenemedi",
    formLabel: (name: string) => `${name} girdileri`,
    selectOption: "Seçin",
    noTargets: "Uygun hedef yok",
    noTargetsEnv: (env: string) => `${env} ortamında hedef yok`,
    onlyEnv: (env: string) => `Yalnız ${env} ortamı`,
    branchNeedsRepo: "Önce bir repo seçin",
  },
  repos: {
    button: "Repo",
    all: "Tüm repolar",
    allHint: "Görev çalışma alanındaki her repoda çalışır",
    count: (n: number) => `${n} repo`,
    none: "Repo yok",
    search: "Repo ara",
    empty: "Repo bulunamadı",
    lastOne: "En az bir repo seçili kalmalı",
    loadFailed: "Repolar yüklenemedi",
  },
  branch: {
    button: "Branch",
    label: "Temel branch",
    default: (name: string) => `${name} (varsayılan)`,
    defaultTag: "varsayılan",
    search: "Branch ara",
    empty: "Branch bulunamadı",
    local: "Yerel",
    remote: "Uzak",
    multiRepo: "Birden çok repo seçiliyken her repo kendi varsayılan branch'inden başlar",
    loadFailed: "Branch'ler yüklenemedi",
    loading: "Branch'ler yükleniyor…",
  },
  advanced: {
    toggle: "Gelişmiş",
    changed: "Gelişmiş ayarlar değiştirildi",
    budget: "Bütçe",
    budgetHint: "Abonelik limitlerinin en fazla ne kadarı kullanılsın",
    fiveHour: "5 saatlik pencere",
    weekly: "Haftalık",
    duration: "Süre tavanı",
    turns: "Tur tavanı",
    minutes: "dk",
    turnsUnit: "tur",
    percentPlaceholder: "sınırsız",
    priority: "Öncelik",
    priorities: { low: "Düşük", normal: "Normal", high: "Yüksek", urgent: "Acil" },
    schedule: "Başlangıç",
    schedules: { now: "Hemen", reset: "Limit sıfırlanınca", at: "Belirli zamanda" },
    scheduleAt: "Başlangıç zamanı",
    flow: "Kayıtlı akış",
    flowNone: "Yok · seçilen modu kullan",
    flowHint: "Seçilirse modun yerine bu akış çalışır",
    flowsEmpty: "Bu çalışma alanında kayıtlı akış yok",
  },
  errors: {
    prompt: "Görevi birkaç cümleyle anlat.",
    required: (label: string) => `“${label}” alanı zorunlu.`,
    percent: "1 ile 100 arasında bir yüzde girin.",
    positiveInt: "Pozitif bir tam sayı girin.",
    scheduleMissing: "Bir başlangıç zamanı seçin.",
    schedulePast: "Başlangıç zamanı gelecekte olmalı.",
    noWorkspace: "Önce bir çalışma alanı oluşturun.",
    team: "Bir ekip seçin.",
  },
  commands: {
    newWithMode: (label: string) => `Yeni görev: ${label}`,
  },
} as const;
