/** Turkish defaults used inside UI kit components. Every one can be overridden by props. */
export const uiStrings = {
  close: "Kapat",
  loading: "Yükleniyor…",
  copy: "Kopyala",
  copied: "Kopyalandı",
  newLines: (n: number) => (n === 1 ? "1 yeni satır" : `${n} yeni satır`),
  jumpToBottom: "En alta git",
  wrap: "Satırları kaydır",
  noOutput: "Henüz çıktı yok.",
  selectPlaceholder: "Seçin",
  resize: "Genişliği ayarla",
  dismiss: "Kapat",
  context: "bağlam",
  input: "giriş",
  output: "çıkış",
  resetsIn: "Sıfırlanma",
  resetUnknown: "Sıfırlanma zamanı bilinmiyor",
  exhausted: "Doldu",
  more: (n: number) => `+${n}`,
  unifiedDiff: "Birleşik",
  splitDiff: "Yan yana",
  additions: (n: number) => `+${n}`,
  deletions: (n: number) => `−${n}`,
  environment: { local: "Yerel", test: "Test", production: "Production" },
  providers: { claude: "Claude", codex: "Codex" },
  agentState: {
    starting: "Başlatılıyor",
    idle: "Boşta",
    thinking: "Düşünüyor",
    responding: "Yanıtlıyor",
    running_tool: "Araç çalıştırıyor",
    waiting_permission: "İzin bekliyor",
    waiting_user: "Yanıt bekliyor",
    interrupted: "Durduruldu",
    done: "Tamamlandı",
    error: "Hata",
  },
  agentRole: {
    writer: "Yazar",
    advisor: "Danışman",
    reviewer: "İnceleyen",
    planner: "Planlayıcı",
    tester: "Test eden",
    judge: "Hakem",
    synthesizer: "Sentezci",
  },
  status: {
    idle: "Boşta",
    running: "Çalışıyor",
    waiting: "Bekliyor",
    success: "Başarılı",
    error: "Hata",
    offline: "Kapalı",
  },
  gate: {
    pending: "Bekliyor",
    running: "Denetleniyor",
    passed: "Geçti",
    failed: "Geçmedi",
    skipped: "Atlandı",
  },
} as const;
