/** Turkish strings for the app chrome. */
import { common } from "@/i18n/common";
import type { ApprovalKind } from "@/lib/types";

export const shellStrings = {
  appName: common.appName,
  sidebar: {
    collapse: "Kenar çubuğunu daralt",
    expand: "Kenar çubuğunu genişlet",
    workspaces: "Çalışma alanları",
    switchWorkspace: "Çalışma alanı değiştir",
    newWorkspace: "Yeni çalışma alanı",
    noWorkspace: "Çalışma alanı yok",
    navigation: "Gezinme",
    gallery: "Bileşen galerisi",
  },
  workspaceDialog: {
    title: "Yeni çalışma alanı",
    description: "Her çalışma alanının kendi hafızası, akışları ve bağlantıları olur.",
    name: "Ad",
    placeholder: "ör. Ödeme servisi",
    create: "Oluştur",
    created: (name: string) => `“${name}” oluşturuldu`,
    empty: "Bir ad girin.",
  },
  topbar: {
    search: "Ara",
    searchHint: "Sayfa, eylem veya ayar ara",
    limits: "Kullanım limitleri",
    approvals: "Onaylar",
    agents: "Etkin ajanlar",
  },
  limits: {
    title: "Kullanım limitleri",
    source: { event: "CLI olayı", probe: "Sorgu", estimate: "Tahmin" } as Record<string, string>,
    updated: (rel: string) => `${rel} güncellendi`,
    empty: "Henüz limit bilgisi yok.",
  },
  approvals: {
    title: "Onay bekleyenler",
    empty: "Bekleyen onay yok",
    emptyHint: "Ajanlar onay istediğinde burada görünür.",
    viewAll: "Tümünü gör",
    approve: "Onayla",
    reject: "Reddet",
    note: "Not (isteğe bağlı)",
    cancel: "Vazgeç",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    failed: "Karar kaydedilemedi",
    production: "Production",
    count: (n: number) => (n === 0 ? "Bekleyen onay yok" : `${n} onay bekliyor`),
    kinds: {
      plan: "Plan onayı",
      memory: "Hafıza önerisi",
      remote_command: "Uzak komut",
      db_write: "Veritabanı yazma",
      deploy: "Deploy",
      merge: "Birleştirme",
      final: "Son onay",
      tool_permission: "Araç izni",
      question: "Ajan sorusu",
      budget: "Bütçe",
      custom: "Onay",
    } satisfies Record<ApprovalKind, string>,
  },
  agents: {
    title: "Etkin ajanlar",
    none: "Etkin ajan yok",
    more: (n: number) => `+${n}`,
    openSessions: "Oturumlara git",
  },
  palette: {
    label: "Komut paleti",
    placeholder: "Bir sayfa, eylem veya ayar arayın…",
    empty: "Sonuç bulunamadı",
    navigateHint: "gezin",
    runHint: "çalıştır",
    closeHint: "kapat",
  },
  connection: {
    banner: common.backendDown,
    reconnected: "Motor bağlantısı yeniden kuruldu",
    online: "Motor bağlı",
    offline: "Motor çalışmıyor",
    connecting: "Bağlanıyor…",
    retry: common.retry,
  },
  production: {
    frame: "Production",
  },
  commands: {
    newTask: "Yeni görev",
    themeLight: "Açık tema",
    themeDark: "Koyu tema",
    themeSystem: "Sistem teması",
    toggleSidebar: "Kenar çubuğunu daralt / genişlet",
    closeDrawer: "Çekmeceyi kapat",
    openApprovals: "Onay kutusunu aç",
    switchTo: (name: string) => `Çalışma alanına geç: ${name}`,
    newWorkspace: "Yeni çalışma alanı oluştur",
    gallery: "Bileşen galerisini aç",
    reduceMotionOn: "Hareketi azalt: açık",
    reduceMotionOff: "Hareketi azalt: sistem",
  },
} as const;
