/** Turkish strings of the task detail and run replay pages. */
import type { FlowMode, GateKind, NodeKind, NodeStatus, RunStatus, TaskStatus } from "./types";

export const s = {
  breadcrumbTasks: "Görevler",
  back: "Görevlere dön",
  backToTask: "Göreve dön",
  retry: "Tekrar dene",
  loadingTask: "Görev yükleniyor",
  notFoundTitle: "Görev bulunamadı",
  notFoundBody: "Bu görev silinmiş ya da hiç var olmamış olabilir.",
  errorTitle: "Görev yüklenemedi",
  sectionError: "Bu bölüm yüklenemedi.",
  engineMissing: "Akış motoru henüz hazır değil.",

  mode: {
    single: "Tek",
    duo: "İkili",
    race: "Yarış",
    pipeline: "Hat",
    council: "Kurul",
    custom: "Özel",
  } satisfies Record<FlowMode, string>,

  taskStatus: {
    draft: "Taslak",
    queued: "Kuyrukta",
    running: "Çalışıyor",
    waiting: "Bekliyor",
    completed: "Tamamlandı",
    failed: "Başarısız",
    cancelled: "İptal edildi",
  } satisfies Record<TaskStatus, string>,

  runStatus: {
    running: "Çalışıyor",
    waiting: "Bekliyor",
    completed: "Tamamlandı",
    failed: "Başarısız",
    cancelled: "İptal edildi",
  } satisfies Record<RunStatus, string>,

  nodeStatus: {
    pending: "Bekliyor",
    running: "Çalışıyor",
    waiting: "Onay bekliyor",
    passed: "Tamamlandı",
    failed: "Başarısız",
    skipped: "Atlandı",
    cancelled: "İptal edildi",
  } satisfies Record<NodeStatus, string>,

  gateStatus: { passed: "Geçti", failed: "Geçmedi", skipped: "Atlandı" } as Record<string, string>,

  nodeKind: {
    agent: "Ajan",
    advisor: "Danışman",
    gate: "Kapı",
    parallel: "Paralel başlat",
    join: "Birleşme",
    compare: "Karşılaştırma",
    condition: "Koşul",
    synthesis: "Sentez",
    merge: "Birleştirme",
    git: "Git",
    deploy: "Deploy",
    human: "Kullanıcı adımı",
  } satisfies Record<NodeKind, string>,

  gateKind: {
    plan_approval: "Plan onayı",
    boundary_check: "Sınır denetimi",
    build_test: "Build/test kanıtı",
    cross_review: "Çapraz inceleme",
    user_final: "Son onay",
    deploy_approval: "Deploy onayı",
    custom_command: "Özel komut",
  } satisfies Record<GateKind, string>,

  gateHint: {
    plan_approval: "Planı kullanıcı onaylar",
    boundary_check: "Diff, sınırlarla karşılaştırılır",
    build_test: "Komutları studiod çalıştırır",
    cross_review: "Farklı sağlayıcı inceler",
    user_final: "Özet, diff ve kanıtlar onaya gelir",
    deploy_approval: "Deploy öncesi onay",
    custom_command: "Komut sıfırla çıkmalı",
  } satisfies Record<GateKind, string>,

  // header
  created: "Oluşturuldu",
  started: "Başladı",
  finished: "Bitti",
  duration: "Süre",
  allRepos: "Tüm repolar",
  showPrompt: "Görev metnini göster",
  hidePrompt: "Görev metnini gizle",
  start: "Başlat",
  startNow: "Hemen başlat",
  startOnReset: "Limit sıfırlanınca başlat",
  rerun: "Yeniden çalıştır",
  queuedHint: "Kuyrukta sırasını bekliyor",
  cancel: "İptal et",
  cancelTask: "Görevi iptal et",
  cancelConfirmTitle: "Görev iptal edilsin mi?",
  cancelConfirmBody: "Çalışan ajanlar durdurulur ve bekleyen onaylar kapatılır. Worktree'ler silinmez.",
  keepRunning: "Devam etsin",
  cancelled: "Görev iptal edildi",
  started_: "Görev başlatıldı",
  queued: "Görev kuyruğa alındı",
  export: "Dışa aktar",
  exportAs: { md: "Markdown (.md)", html: "HTML (.html)", json: "JSON (.json)" },
  exportDone: (name: string) => `${name} indirildi`,
  exportFailed: "Dışa aktarılamadı",
  more: "Diğer eylemler",
  openReplay: "Tekrar oynatmayı aç",
  copyId: "Görev kimliğini kopyala",
  copied: "Kopyalandı",
  hold: (reason: string) => `Beklemede: ${reason}`,

  // quality
  quality: "Kalite puanı",
  qualityNone: "Puan, koşu tamamlanınca hesaplanır.",
  qualityProvisional: "Ara puan: koşu sürüyor, şimdiye kadarki kapılara göre.",
  provisional: "ara",
  qualityFormula: "Formül",
  qualityNa: "uygulanmadı",
  weight: (w: number) => `%${Math.round(w)} ağırlık`,
  rate: "Puan ver",
  rateLabel: (n: number) => `${n} yıldız`,
  rated: (n: number) => `Görev ${n} yıldızla puanlandı`,
  rateFailed: "Puan kaydedilemedi",
  yourRating: "Senin puanın",

  // flow
  flow: "Akış",
  flowProgress: (done: number, total: number) => `${done}/${total} adım`,
  flowPreview: "Önizleme: görev başlayınca bu akış çalışacak.",
  flowEmpty: "Bu görev için akış grafiği yok.",
  fitView: "Tümünü sığdır",
  focusActive: "Etkin düğüme git",
  run: "Koşu",
  runN: (n: number, total: number) => `Koşu ${n}/${total}`,
  handoff: "devrediliyor",
  round: (n: number) => `Tur ${n}`,
  loopBack: (n: number) => `geri döndü · tur ${n}`,
  canvasLabel: "Akış ilerlemesi",
  notStartedTitle: "Görev henüz başlamadı",
  notStartedBody: "Başlattığında akış burada canlı ilerler.",

  // tabs
  tabNode: "Düğüm",
  tabChanges: "Değişiklikler",
  tabGates: "Kapılar",
  tabCheckpoints: "Checkpoint'ler",

  // node panel
  noNodeTitle: "Bir düğüm seç",
  noNodeBody: "Akıştaki bir adıma tıklayınca ayrıntıları burada görünür.",
  attempt: "Deneme",
  retryNode: "Yeniden dene",
  retried: (label: string) => `${label} yeniden deneniyor`,
  retryFailed: "Düğüm yeniden denenemedi",
  agents: "Ajanlar",
  noAgents: "Bu adımda henüz ajan oturumu yok.",
  openSession: "Canlı çıktıyı aç",
  output: "Çıktı",
  noOutput: "Bu adım henüz çıktı üretmedi.",
  showMore: "Tamamını göster",
  showLess: "Daralt",
  error: "Hata",
  waitingFor: "Bekleniyor",
  waitingApproval: "Onay bekleniyor",
  decideAbove: "Kararını sayfanın üstündeki onay kutusundan verebilirsin.",
  gateChecking: "Kapı denetleniyor…",
  gateDeciding: "Karar bekleniyor…",
  now: "Şu an",
  progress: "İlerleme",
  agentEvidence: "Ajanın eklediği kanıtlar",
  gateEvidence: "Kapı kanıtı",
  decidedBy: (who: string) => `Karar: ${who}`,
  decider: { studiod: "studiod", user: "kullanıcı" } as Record<string, string>,
  pendingNode: "Bu adım sırasını bekliyor.",
  skippedReason: { disabled: "Kapı bu akışta kapalı.", nothing_to_check: "Denetlenecek bir şey yoktu.", dead_path: "Bu dala hiç gelinmedi." } as Record<string, string>,

  // gate evidence
  commands: "Komutlar",
  exitCode: (c: number) => `çıkış ${c}`,
  timeout: "zaman aşımı",
  runner: "Komutları ajan değil studiod çalıştırdı.",
  findings: "Bulgular",
  noFindings: "Bulgu yok.",
  blocking: "engelleyici",
  severity: { critical: "Kritik", high: "Yüksek", medium: "Orta", low: "Düşük" } as Record<string, string>,
  reviewer: "İnceleyen",
  author: "Yazar",
  verdict: { pass: "Geçti", fail: "Geçmedi" } as Record<string, string>,
  violations: "Sınır ihlalleri",
  noViolations: "Sınır ihlali yok.",
  violationKind: { forbidden: "yasak yol", readonly: "salt okunur yol", denied_command: "yasak komut" } as Record<string, string>,
  rule: "kural",
  changedFiles: (n: number) => `${n} değişen dosya`,
  commandsChecked: (n: number) => `${n} komut`,
  approval: "Onay",
  approvalStatus: { approved: "Onaylandı", rejected: "Reddedildi", expired: "Süresi doldu", cancelled: "İptal edildi", pending: "Bekliyor" } as Record<string, string>,
  editedPlan: "Kullanıcı planı düzenledi",
  note: "Not",
  production: "Production",
  profiles: "Deploy profilleri",
  file: "Dosya",
  message: "Bulgu",

  // approvals
  approvalsTitle: (n: number) => (n === 1 ? "Onayın bekleniyor" : `${n} onay bekleniyor`),

  // changes
  worktrees: "Worktree'ler",
  noChangesTitle: "Henüz değişiklik yok",
  noChangesBody: "Kod yazan ajanlar çalıştıkça worktree'leri ve diff'leri burada görünür.",
  files: (n: number) => (n === 1 ? "1 dosya" : `${n} dosya`),
  selectFile: "Bir dosya seç",
  binaryFile: "İkili dosya — metin diff'i gösterilemiyor.",
  largeFile: "Dosya çok büyük; diff gösterilmiyor.",
  truncated: "Diff çok büyük olduğu için kısaltıldı.",
  mergePreview: "Birleştirme önizlemesi",
  mergeClean: "Çakışma yok",
  mergeConflicts: (n: number) => (n === 1 ? "1 çakışma" : `${n} çakışma`),
  into: "→",
  openInEditor: "Editörde aç",
  revealInFinder: "Finder'da göster",
  copyPath: "Yolu kopyala",
  fileTree: "Değişen dosyalar",
  worktreeStatus: { active: "Etkin", merged: "Birleşti", abandoned: "Terk edildi", removed: "Silindi" } as Record<string, string>,
  conflictToast: (repo: string) => `${repo}: birleştirmede çakışma bulundu`,
  diffOf: (path: string) => `${path} diff'i`,

  // gates tab
  noGatesTitle: "Henüz kapı sonucu yok",
  noGatesBody: "Kapılar çalıştıkça kanıtlarıyla birlikte burada listelenir.",

  // checkpoints
  noCheckpointsTitle: "Henüz checkpoint yok",
  noCheckpointsBody: "Her adım bittiğinde worktree'lerin ve hafızanın anlık görüntüsü alınır.",
  restore: "Geri dön",
  restoreTitle: "Bu checkpoint'e geri dönülsün mü?",
  restoreBody: (label: string) =>
    `Worktree'ler "${label}" anına sıfırlanır ve koşu oradan devam eder. Sonraki değişiklikler kaybolur.`,
  restoreConfirm: "Geri dön",
  restored: (label: string) => `"${label}" anına geri dönüldü`,
  restoreFailed: "Checkpoint'e geri dönülemedi",
  refs: (n: number) => (n === 1 ? "1 worktree" : `${n} worktree`),
  memoryCommit: "hafıza",

  // usage
  usage: "Kullanım",
  tokens: "Token",
  input: "Giriş",
  outputTokens: "Çıkış",
  turns: "Tur",
  window5h: "5 saat",
  windowWeekly: "Haftalık",
  ofWindow: (label: string) => `${label} penceresinden`,
  budget: "Bütçe",
  budgetOf: (p: number) => `tavan %${p}`,
  noUsage: "Henüz kullanım kaydı yok.",

  // runs
  runs: "Koşular",
  current: "güncel",
  replay: "Tekrar oynat",

  // palette
  cmd: {
    cancel: "Görevi iptal et",
    start: "Görevi başlat",
    exportMd: "Görevi Markdown olarak dışa aktar",
    exportHtml: "Görevi HTML olarak dışa aktar",
    exportJson: "Görevi JSON olarak dışa aktar",
    openDiff: "Görevin değişikliklerini aç",
    openReplay: "Görevin tekrar oynatmasını aç",
    retryFailed: "Başarısız düğümü yeniden dene",
    group: "Bu görev",
  },

  // replay
  replayTitle: "Tekrar oynatma",
  replayLoading: "Zaman çizelgesi yükleniyor",
  replayError: "Zaman çizelgesi yüklenemedi",
  replayNotFound: "Koşu bulunamadı",
  replayEmpty: "Bu koşuda oynatılacak olay yok.",
  play: "Oynat",
  pause: "Duraklat",
  restart: "Baştan oynat",
  speed: "Hız",
  live: "Canlı",
  followLive: "Canlıyı izle",
  scrubber: "Zaman çizelgesi",
  prevMoment: "Önceki önemli an",
  nextMoment: "Sonraki önemli an",
  events: "Olaylar",
  keyEvents: "Önemli",
  allEvents: "Tümü",
  stateAt: "Bu andaki durum",
  agentsAt: "Ajanlar",
  gatesAt: "Kapılar",
  noAgentsYet: "Bu anda çalışan ajan yok.",
  gap: (d: string) => `${d} boşluk`,
  eventCount: (n: number) => `${n} olay`,
  prevNextEvent: "olay",
} as const;

/** Readable decider: "user" → "kullanıcı", "agent:codex" → "Codex". */
export function deciderLabel(who: string): string {
  if (who.startsWith("agent:")) {
    const p = who.slice(6);
    return p === "claude" ? "Claude" : p === "codex" ? "Codex" : p;
  }
  return s.decider[who] ?? who;
}
